### ISSUE TITLE
Missing channels from package.yaml definition

### ISSUE THREAD

**Issue by eguzki** [operator-framework/operator-lifecycle-manager#1072]
## Bug Report

Openshift 4.1

Not sure about running OLM version:
```
$ oc get deployment -n openshift-operator-lifecycle-manager olm-operator -o yaml | yq r - spec.template.spec.containers.*.image
- quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ca6b07b6d742088552889755160089bfde1301629f60746c453600b8a0ddebae
```

The issue is about declaring 3 channels (also tried with 4 channels), and dashboard only shows 2 of them. `packagemanifest` resource only shows 2 channels

This is the package.yaml with 3 channels
```
packageName: 3scale-operator27                                
channels:                                                                    
  - name: beta                                                
    currentCSV: 3scale-operator27.v0.4.0                      
  - name: threescale-2.6                                      
    currentCSV: 3scale-operator27.v0.3.0                      
  - name: threescale-2.7                                      
    currentCSV: 3scale-operator27.v0.4.0                      
defaultChannel: threescale-2.6                                
```
After creating the operator source, `packagemanifest` resource only shows two channels.

```
$ oc get packagemanifests -n openshift-marketplace 3scale-operator27 -o yaml | yq r - status.channels.*.name
- beta
- threescale-2.6
```

I was expecting to have all 3 channels.

Related issue with this issue is that when the missing channel is the one set as `defaultChannel`, (threescale-2.6 in the example above), then when we try to create operator subscription using marketplace UI, the screen gets white without any controls.
