### ISSUE TITLE
catalog-operator long delay to report correct status.connectionState.lastObservedState on re-created CatalogSource

### ISSUE THREAD

**Issue by dacleyra** [operator-framework/operator-lifecycle-manager#1098]
## Bug Report

**What did you do?**

* Create a CatalogSource
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kabanero-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: kabanero/kabanero-operator-registry:0.3.0-alpha.1
  publisher: kabanero.io
  displayName: Kabanero Operators
```

* Check the state
```
oc get catalogsource kabanero-catalog -n openshift-marketplace --output=jsonpath={.status.connectionState.lastObservedState}
READY
```

* Delete the CatalogSource

* Re-Create the CatalogSource

* Check the state
```
oc get catalogsource kabanero-catalog -n openshift-marketplace --output=jsonpath={.status.connectionState.lastObservedState}
CONNECTING
```

* Check the catalog-operator

```
time="2019-10-29T20:10:43Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=kabanero-catalog state.State=CONNECTING"
time="2019-10-29T20:10:46Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=kabanero-catalog state.State=TRANSIENT_FAILURE"
time="2019-10-29T20:10:47Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=kabanero-catalog state.State=CONNECTING"
time="2019-10-29T20:11:02Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=kabanero-catalog state.State=READY"
time="2019-10-29T20:11:50Z" level=info msg="Adding related objects for operator-lifecycle-manager-catalog"
time="2019-10-29T20:16:55Z" level=info msg="Adding related objects for operator-lifecycle-manager-catalog"
time="2019-10-29T20:22:00Z" level=info msg="Adding related objects for operator-lifecycle-manager-catalog"
```

**What did you expect to see?**

The catalog-operator logs indicate the re-created CatalogSource is READY.
I expect the `.status.connectionState.lastObservedState` to be updated to READY

**What did you see instead? Under which circumstances?**

For the re-created CatalogSource,
The `.status.connectionState.lastObservedState` is not updated to READY, and is left at CONNECTING for about 10 minutes
It seemed to roll over to READY again around the time of the 3rd `Adding related objects` 

**Environment**
* operator-lifecycle-manager version: 0.11.0

* Kubernetes version information: v1.14.6+2e5ed54

* Kubernetes cluster kind: OCP 4.2.0

OLM 0.12.0 was also attemped, as I suspected it may be related to
https://github.com/operator-framework/operator-lifecycle-manager/issues/947

**Possible Solution**

**Additional context**
