### ISSUE TITLE
InstallPlans not being generated on OpenShift 3.11 with OLM 0.12.0

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-lifecycle-manager#1113]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Upgrade of OLM on OpenShift 3.11

## Question
I have upgraded OLM to 0.12.0 on OpenShift 3.11 and my subscriptions seem to be stuck. The Subscription status is with notes about two healthy catalogs. No InstallPlans exist across the entire cluster.
```
  conditions:
  - lastTransitionTime: 2019-11-07T15:09:18Z
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
```

Why aren't my InstallPlans being created? 

**What did you do?**
I paused the deployments of OLM 0.6.0 pods in the operator-lifecycle-manager namespace and scaled them down to 0. 
I ran oc create -f on the 0.12.0 crds.yaml and olm.yaml files. 
I added our custom CatalogSource.
I created a Subscription to an operator in our catalog.

**What did you expect to see?**
The operator install into the operators namespace and get running.

**What did you see instead? Under which circumstances?**
The Subscription status seems to halt after noting healthy catalogs (CatalogSourcesUnhealthy:False). 

**Environment**
* operator-lifecycle-manager version:
OLM version: 0.12.0
git commit: a611449366805935939777d0182a86ba43b26cbd

* Kubernetes version information:

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://XXXXXXXXXXXXX:8443
openshift v3.11.153
kubernetes v1.11.0+d4cacc0
  

* Kubernetes cluster kind: 
OpenShift

**Additional context**
I'm glad to provide whatever is needed. 

I've confirmed with grpcurl that the catalog pods are responding with correct data. 
In the catalog operator logs, I've found this regarding my operator subscription: `msg=syncing event=update reconciling="*v1alpha1.Subscription"`
