### ISSUE TITLE
Can't install APIService that doesn't introduce a new Kind

### ISSUE THREAD

**Issue by zroubalik** [operator-framework/operator-lifecycle-manager#1122]
## Bug Report

**What did you do?**
Created `CSV` for operator that internally uses APIService object to extend k8s metrics.
Operator is using `APIService` listed below, relevant files such as `ClusterRoles` are located in [this repo](https://github.com/zroubalik/keda/tree/olm/deploy). Manual installation (`oc apply -f deploy/`) is working correctly and Operator is fully functional.
```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: keda-operator
    namespace: keda
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```
Keda operator implements [external metrics apiserver framework](https://github.com/kubernetes-incubator/custom-metrics-apiserver) interface. Keda Operator is following the instructions and deployment recomendations (`APIService`, `ClusterRole`, etc) specified in the framework. 

I tried to map `APIService` specified above to the respective fields in the `CSV`, this is the relevant part:
```
  apiservicedefinitions:
    owned:
    - group: external.metrics.k8s.io
      kind: 
      version: v1beta1
      displayName: Metrics Server APIService
      description: Metrics Server APIService which is used internally by Keda.
      deploymentName: keda-operator
      containerPort: 6443  
      specDescriptors: []    
```
I am not sure what should I specify under `kind` and in fact, this is the part that is causing the problems after the deployment. This deployment doesn't introduce any new `Kind`, it is extending k8s metrics server. This operator is not defining a new extenstion. it is just providing an implementation to existing one.

CSV and package is located [here](https://github.com/zroubalik/keda/blob/olm/deploy/olm-catalog/keda/0.0.4/keda.v0.0.4.clusterserviceversion.yaml)

**What did you expect to see?**
Successful installation.

**What did you see instead? Under which circumstances?**
Operator is installed and fully functional, all objects are correctly created. But due to unsuccessful installation, OLM is trying to restart the operator periodically every few minutes, which results in redeployment of the operator pod.
Restarts happen because of problems in api discovery, caused by not specified `kind` in `CSV`.

Relevant log snippet from `olm-operator` pod:
```
time="2019-11-12T20:33:15Z" level=info msg="csv in operatorgroup" csv=keda.v0.0.4 id=vlRUk namespace=openshift-operators opgroup=global-operators phase=Installing
time="2019-11-12T20:33:15Z" level=info msg="couldn't find GVK in api discovery" group=external.metrics.k8s.io kind= version=v1beta1
```

**Environment**
* operator-lifecycle-manager version:
4.2.0-0.nightly-2019-09-17-232025

* Kubernetes version information:
v1.14.6+e353665

* Kubernetes cluster kind: 
OCP     4.2.0-0.nightly-2019-09-17-232025

**Possible Solution**
Allow users to disable discovery for specified resource, in this case `APIService`.

**Additional context**
https://github.com/kubernetes-incubator/custom-metrics-apiserver
https://kubernetes.io/docs/tasks/access-kubernetes-api/#register-apiservice-objects

**Comment by awgreene** [comment]
Thanks for submitting this issue @zroubalik.

Your CSV is failing to reach the succeeded state because your `apiservicedefinition` is missing a `KIND`. OLM relies on [GroupVersionKind (GVK)](https://github.com/operator-framework/operator-lifecycle-manager/blob/ba10413e72cfe23724edc588ff25f36dfdbeb37e/pkg/controller/operators/olm/requirements.go#L384:20) to ensure that the `apiservice` is working as expected and for [dependency resolution](https://operator-framework.github.io/olm-book/docs/operator-dependencies-and-requirements)

I looked into what `KIND` your CSV provides and found that when your operator is deployed and no [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) is created, an empty list of resources are defined:
```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

At this point, the installation fails because of [this check in OLM](https://github.com/operator-framework/operator-lifecycle-manager/blob/ba10413e72cfe23724edc588ff25f36dfdbeb37e/pkg/controller/operators/olm/requirements.go#L404) because no resources exist.

When your operator is used it will eventually create an HPA which in turn defines a new resource:
```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "lagThreshold",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

Now that a `resource` exists - updating your CSV's `apiservicedefinitions` to list a `KIND` and `NAME` will lead to a successful install:
```
apiservicedefinitions:
  owned:
  - containerPort: 6443
    deploymentName: keda-server
    description: Metrics Server APIService which is used internally by Keda.
    displayName: Metrics Server APIService
    group: external.metrics.k8s.io
    kind: ExternalMetricValueList
    name: externalmetricvaluelist
    version: v1beta1
```

At this point, OLM cannot remove the restraint on the `GVK` due to the fact that dependency resolution would be broken as a result.
