### ISSUE TITLE
OLM picks an operator dependency randomly for operators handling same resources kind provided by the same CatalogSource

### ISSUE THREAD

**Issue by ppatierno** [operator-framework/operator-lifecycle-manager#1158]
## Bug Report

A Strimzi user reported this issue on our project https://github.com/strimzi/strimzi-kafka-operator/issues/2265 and it seems that the OLM selects which operator dependency to use quite randomly.
The Strimzi and the AMQ Streams operators handle the same resources kind in this specific use case, but which dependency is used isn't deterministic.

**What did you do?**

Specifying requirements for an operator in this way.

```yaml
required:
    - description: Represents a Kafka cluster
      displayName: Kafka
      kind: Kafka
      name: kafkas.kafka.strimzi.io
      version: v1beta1
    - description: Represents a topic inside a Kafka cluster
      displayName: Kafka Topic
      kind: KafkaTopic
      name: kafkatopics.kafka.strimzi.io
      version: v1beta1
```

**What did you expect to see?**
The OLM should always pick the same operator dependency.

**What did you see instead? Under which circumstances?**
The OLM should always pick an operator dependency randomly.

**Environment**

Strimzi version: 0.14.0 (AMQ Streams 1.3.0)
Installation method: OperatorHub.io
Kubernetes cluster: OpenShift 4.2
Infrastructure: CRC
