### ISSUE TITLE
`spec.name` -> `spec.packageName`

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1167]
For subscription, we are now using `name` to identify the name of the package https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/api/apis/operators/v1alpha1/subscription_types.go#L34 , an example is as follows:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-operator-subsription
  namespace: marketplace
spec:
  channel: <channel-name>
  name: my-operator <<<<
  source: johndoe-operators
  sourceNamespace: marketplace
```

But the `spec.name` is difficult to understand it means the package name, how about rename this to `spec.packageName` which is more meaningful?

FYI @clyang82
