### ISSUE TITLE
Can I specify namespace in "required" operators  in clusterserviceversion 

### ISSUE THREAD

**Issue by clyang82** [operator-framework/operator-lifecycle-manager#1191]
## Bug Report

**What did you do?**

I have an operator (OpA) depends on another operator (OpC), so in OpA `clusterserviceversion` file, I use `required` to achieve this goal. for example:
```
customresourcedefinitions:
    owned:
    - description: A configuration file for a Jaeger custom resource.
      displayName: Jaeger
      kind: Jaeger
      name: jaegers.jaegertracing.io
      version: v1
    required:
    - description: An Elasticsearch cluster instance
      displayName: Elasticsearch
      kind: Elasticsearch
      name: elasticsearches.logging.openshift.io
      version: v1
```

I have another operator (OpB) also depends on OpC, so in OpB `clusterserviceversion` file, I use `required` to achieve this goal.

follow the above way, the OpC is installed twice in both namespace of OpA and namespace of OpB.

**What did you expect to see?**

Can I have only one OpC instance installed in the cluster? in other word, if the OpB finds that the OpC was installed, then just skip OpC installation.

I did not find there can specify the `namespace` for `required` operator.

Any suggestions? Thanks.
