### ISSUE TITLE
configmap-registry-server readinessProbe is to small causing crashes

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1238]
## Bug Report

The configmap-registry-server readinessProbe timeoutSeconds is hardcoded to `1` here:  https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/controller/registry/reconciler/configmap.go#L91-L97

On a cluster that is very slow, this can cause many pod restarts.    
```
Readiness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 1s exceeded: context deadline exceeded
or
Readiness probe failed: timeout: failed to connect service "localhost:50051" within 1s

Warning  BackOff    9m9s (x343 over 3h36m)  kubelet, 10.130.227.126  Back-off restarting failed container
```
**What did you do?**
Created a catalog source: 
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-catalog-source
  namespace: my-namespace
spec:
  sourceType: configmap
  configMap: addon-catalog-manifests
```
**What did you expect to see?**
A higher value for the timeout or a way to configure this thru the catalog source resource.

**What did you see instead? Under which circumstances?**

catalog source pod is restarting frequently.

**Environment**
* operator-lifecycle-manager version:

0.13.0

* Kubernetes version information:

1.16

* Kubernetes cluster kind: 

IBM Cloud

**Possible Solution**

**Additional context**

**Comment by kramvan1** [comment]
Readiness probe:
```
readinessProbe:
      exec:
        command:
        - grpc_health_probe
        - -addr=localhost:50051
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```
This execd cmd can sometimes take more then 1 second.
