### ISSUE TITLE
Unable to specify ImagePullSecrets for private registry in ClusterServiceVersion

### ISSUE THREAD

**Issue by secat** [operator-framework/operator-lifecycle-manager#1294]
I have generated a CSV for my custom operator using the `operator-sdk generate csv` command. After inspecting the CRD definition for CSV (ClusterServiceVersion) custom resource, I didn't find a way to pass a configuration for `ImagePullSecrets` for the `clusterserviceversion.spec.install.spec.permissions.serviceAccountName`.

The image for my custom operator is in a private registry and I need to have an automated way to pass my private registry credentials.

Without proper `ImagePullSecrets` the pod created for my operator deployment by the OLM gets stuck with `ImagePullBackOff`.

Is there something that I can configure for that? Is it something that is currently missing?

I am currently using:
- operator-sdk: v0.15.0
- operator lifecycle manager: quay.io/operator-framework/olm@sha256:0d15ffb5d10a176ef6e831d7865f98d51255ea5b0d16403618c94a004d049373
- kubernetes: v1.15.5 (docker desktop)

**Comment by ecordell** [comment]
Secrets can be specified on the `CatalogSource` that packages up your operator for installation in the cluster.

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-catalog
  namespace: default
spec:
  name: my-catalog
  sourceType: grpc
  image: <your catalog image>
   secrets:
  - my-pull-secret
```

Be aware that if you do this, the secret will be copied into whichever target namespace you install the operator.

Here's a link to an example (the commit removes, rather than adds, pull secrets: https://github.com/operator-framework/operator-lifecycle-manager/commit/0dc8e60f298a468f306d11f13dbd38489e8c573b)
