### ISSUE TITLE
OwnNamespace operator cannot depend on AllNamespaces operator

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1393]
## Bug Report

**What did you do?**

I have two operators, operator1 is with `OwnNamespace` as true and operator2 is `AllNamespaces` is true.

```
installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
```

```
installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
```

operator1 require operator2, then when install operator1, it report the following error:

```
Failed: OwnNamespace InstallModeType not supported, cannot configure to watch own namespace
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by dinhxuanvu** [comment]
Unfortunately, OLM resolver doesn't take in account InstallModes into the dependency resolution. So it depends on the operator authors to ensure all involved operators and the namespace to be compatible with InstallModes.

**Comment by VannTen** [comment]
Hi,

If I read that correctly, we can't use OLM to handle the dependency on a global install of a cluster operator ?

For example, if I want to use a Prometheus CR, I can't use this 
```yaml
properties:
- type: olm.gvk.required
  value:
    group: monitoring.coreos.com
    kind: Prometheus
    version: v1
- type: olm.gvk.required
  value:
    group: monitoring.coreos.com
    kind: PrometheusRule
    version: v1
```
To communicate the intention: "I need a prometheus-operator available in cluster, otherwise my operator will not work" ?
