### ISSUE TITLE
Include StatefulSet as Resource owned by Operand

### ISSUE THREAD

**Issue by rodrigovalin** [operator-framework/operator-lifecycle-manager#1449]
## Feature Request

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When visiting my Operand, and under the `Resources` tab, I don't see all the resources owned by the Operand. In our particular case, we are missing a list of owned `StatefulSet`s. I can only see `Service`s.

This particular case relates to the MongoDB Enterprise Operator, which is based on `StatefulSet`s holding the different `Pod`s with MongoDB Servers on them. As an example, using the latest MongoDB operator 1.4.5 installed via "Operators", and after creating a MongoDB Replica Set (called "my-replica-set") I get:

<img width="850" alt="missing-sts" src="https://user-images.githubusercontent.com/124291/79453829-20550280-7fe2-11ea-8cc0-ceb9a075660e.png">

Which is only showing 1 Service, but unfortunatelly, no `StatefulSet`s. I see this "Resources" section to be valuable to users to understand the whole structure of their MongoDB deployments, and ultimatelly required to navigate the different components of their deployment.

I expect other StatefulSet based operators to benefit from this.

**Comment by ecordell** [comment]
Two things need to happen for it to show up:

- "StatefulSet" needs to be listed in the `resources` block of crddescription section for the related CRD on the CSV
- The statefulset needs to have an owerreference to the owner CR (in this case, the mongodb instance)

These are steps that need to be taken by the operator author / packager. Happy to help with any questions around that process, but the feature itself exists already 😄

**Comment by rodrigovalin** [comment]
Thanks for the information @ecordell 

Can you confirm the following snippet would work in this case? I added a `resources` section to `MongoDB Deployment` declaring both `StatefulSet` (`apps/v1`) and `Service` (`v1`) as dependant resources. The `ownerreference` is set on both Statefulset and services.

```yaml
spec:
  customresourcedefinitions:
    owned:
    - description: MongoDB Deployment
      displayName: MongoDB Deployment
      group: mongodb.com
      kind: MongoDB
      name: mongodb.mongodb.com
      version: v1
      resources:
        - kind: StatefulSet
          version: apps/v1
          name: ''
        - kind: Service
          version: v1
          name: ''
```

Waiting on this for our 1.5 release. Thanks in advance!
