### ISSUE TITLE
How to communicate with application registry without OperatorSource

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [operator-framework/operator-lifecycle-manager#1450]
## Type of question
General question.

## Question
Looks like OperatorSource dropped like deprecated. At least I see crd of the Operator source is not included to the OLM installation. Earlier we could use Operator source to connect to the application registry :

```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: eclipse-che-preview-openshift
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  endpoint: 'https://quay.io/cnr'
  registryNamespace: eclipse-che-operator-openshift
  type: appregistry
```

What should we change to make this feature working without OperatorSource?
