### ISSUE TITLE
correction in the relatedImages proposal regarding OLM annotations

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-lifecycle-manager#1456]
I just want to report a correction on the relatedImages proposal doc:

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md

OLM must create the annotations in the pod template, not on the Deployment itself. So "metadata.annotations" has to be moved to "spec.template.metadata.annotations"

This is because the fieldRefs that refer to annotations are referring to annotations on the Pod not the Deployment.

To see this, download this [test.yaml.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4493942/test.yaml.txt) and apply it:

```
$ oc create namespace atest
$ oc apply -n atest -f test.yaml.text
```

Now run this to see what the value is for env var "FROM_ANNOTATION":

```
$ oc exec -n atest $(oc get pods -n atest -o name) env | grep FROM_ANNOTATION
FROM_ANNOTATION=quay.io/coreos/etcd@sha256:12345
```

That's correct. But notice in my attached file, the annotation is on the pod template, not the deployment. But following the relatedImages proposal document, let's move those annotations up to the Deployment... so this:

```
kind: Deployment
metadata:
  name: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
      annotations:
        olm.relatedImage.etcd-2.1.5: quay.io/coreos/etcd@sha256:12345
```

becomes this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  annotations:
    olm.relatedImage.etcd-2.1.5: quay.io/coreos/etcd@sha256:12345
spec:
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
```

Now try it again:

```
$ oc apply -n atest -f test.yaml.txt 
....wait for the old pod to terminate and new pod to start up...
$ oc exec -n atest $(oc get pods -n atest -o name) env | grep FROM_ANNOTATION
FROM_ANNOTATION=
```

Now notice the env var is empty.

Thus, the proposal needs to change - OLM needs to create those annotations on the pod template, not the deployment itself.
