### ISSUE TITLE
InstallPlan/Update spam with multiple catalogsources containing different operator versions

### ISSUE THREAD

**Issue by lallinger-arbeit** [operator-framework/operator-lifecycle-manager#1471]
## Bug Report

**What did you do?**
On OKD 4.3 i installed the operatorhub.io catalogsource in to an namespace in addition to the preinstalled community-operators.

operatorhub.io catalogsource:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
spec:
  displayName: OperatorHub.io
  image: 'quay.io/operator-framework/upstream-community-operators:latest'
  publisher: OperatorHub.io
  sourceType: grpc
```

Then i installed Noobaa from the operathub.io catalogsource, because it is not listed in the provided community-operator catalogsource (also see [this issue](https://github.com/openshift/okd/issues/99) and [this issue](https://github.com/operator-framework/community-operators/issues/1584)). Noobaa automatically also installs the AWS S3 operator, which is available in both catalogsources in 2 different versions (1.0.0 and 1.0.1).

**What did you expect to see?**
I expected that the higher version 1.0.1 gets installed/updated to.

**What did you see instead? Under which circumstances?**
When having set the installPlanApproval of the AWS S3 operator to automatic it kept going to install version 1.0.1, then 1.0.0, then 1.0.1...... With every update a new serviceaccount and a new rolebinding was created leading to about 2000 objects over night.

When having set the installPlanApproval to manual many installPlans get created (about 4000 over night). Example installPlan:

```
apiVersion: operators.coreos.com/v1alpha1
kind: InstallPlan
metadata:
  creationTimestamp: "2020-04-17T09:10:33Z"
  generateName: install-
  generation: 1
  name: install-9grr7
  namespace: noobaa
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: Subscription
    name: noobaa
    uid: fa1e86ee-a111-4a26-a61e-f503b793da08
  resourceVersion: "2546748"
  selfLink: /apis/operators.coreos.com/v1alpha1/namespaces/noobaa/installplans/install-9grr7
  uid: c3d69d61-1171-49a1-9653-8e4cefc92b50
spec:
  approval: Manual
  approved: false
  clusterServiceVersionNames:
  - awss3operator.v1.0.1
  - awss3operator.v1.0.0
  generation: 4287
```

**Environment**
* operator-lifecycle-manager version:

OLM version delivered with OKD 4.3. I'm not able to directly find the version in the pod details or logs. If anyone can provide instructions to retrive the version i'm glad to add it here.

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"172d22b", GitTreeState:"clean", BuildDate:"2020-04-14T18:40:38Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by dmesser** [comment]
I have just tried this on an OCP 4.3 cluster (4.3.13) and it is not reproducing. From what I can see Noobaa actually depends on objectbucketclaims.objectbucket.io provided lib-bucket-provisioner, which is available from both catalogs. For me Noobaa gets installed alongside lib-bucket-provisioner. The awss3operator does not provide objectbucketclaims.objectbucket.io but actually requires it. For me both awss3operator and lib-bucket-provisioner are available in the same versions from both the OCP community catalog and operatorhubio-catalog. In any case, awss3operator should not get installed as a result of installing Noobaa.
Are you sure that is what happened? On which z-stream version of OKD are you? In which namespaces did you create the operatorhubio-catalog (note that it is not supported / intended for OpenShift)?

**Comment by lallinger-arbeit** [comment]
I'm installing the operathub.io catalogsource in the namespace noobaa, which i created.
catalogsource:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: noobaa
spec:
  displayName: OperatorHub.io
  image: 'quay.io/operator-framework/upstream-community-operators:latest'
  publisher: OperatorHub.io
  sourceType: grpc
```
Then i apply the noobaa operator via subscription:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: noobaa-operatorgroup
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
  - noobaa
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noobaa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: alpha
  name: noobaa-operator
  source: operatorhubio-catalog
  sourceNamespace: noobaa
  installPlanApproval: Automatic
```
With this noobaa and the aws s3 operator are installed. There is a short appearence of a second instance of the aws s3 operator in the installed operators tab, which says aws s3 operator can not update because catalog source was removed and this second instance is provided by red hat and states version 1.0.0. After that the aws s3 operator is updated to 1.0.1 and states provided by community.
It currently looks like on both catalog sources now the aws s3 operator is available in version 1.0.1 (was not the case a few days ago). This may solve my problem currently, but i'm not sure if this won't happen again if the versions divert again. Also i think this error would be possible with other tools too.

I'm using OKD4 Beta 3.

Why is it not supported to install the operatorhub.io catalog in a namespace?
