### ISSUE TITLE
Catalogsource cannot be created via private docker registry

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1505]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-operators
  namespace: openshift-marketplace
spec:
  displayName: My Operators
  sourceType: grpc
  image: my/catalog-test:0.0.1
```

If I push the image `my/catalog-test:0.0.1` to a private registry, then there is no place to enable me to set a imagepullsecrets for this image, and this will cause the catalogsource deploy failed.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by gyliu513** [comment]
Can any expert show some comments for this? Thanks!

**Comment by skuffe** [comment]
Take a look at #1294

**Comment by greglanthier** [comment]
I'm stumbling on this as well with OLM v 0.16.1 in a plain vanilla `kind` cluster & `operator-sdk` v 1.0.1.

In my case I declared a CatalogSource like this:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloudcar-catalog
  namespace: foo
spec:
  displayName: Cloudcar Operators
  sourceType: grpc
  publisher: cloudcar
  image: us.icr.io/ca-sci/cloudcar-operators-index:latest
  secrets:
    - registry-read
  updateStrategy:
    registryPoll:
      interval: 10m
```

assuming that the pre-existing `registry-read` pull secret in the `foo` namespace would be used to pull the index image from my private registry.  Instead the image pulls failed with events like this:

```bash
Failed to pull image "us.icr.io/ca-sci/cloudcar-operators-index:latest": rpc error: code = Unknown desc = failed to pull and unpack image "us.icr.io/ca-sci/cloudcar-operators-index:latest": failed to resolve reference "us.icr.io/ca-sci/cloudcar-operators-index:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

Once I added the `registry-read` secret to the default service account in the `foo` namespace the index image was successfully pulled.

I don't know if this is the right solution (or if its even recommended practice?). After reading https://github.com/operator-framework/operator-lifecycle-manager/issues/1294#issuecomment-587146658 it looks like there may be use cases where using the `secrets` element in `CatalogSource` are _not_recommended?

I dug around in the catalog operator code to see if I could find how the catalog pods are created when a `CatalogSource` is added to a namespace and found this:

https://github.com/operator-framework/operator-lifecycle-manager/blob/6d26c16166b232561132985e1132fce4b4d36532/pkg/controller/registry/reconciler/reconciler.go#L94-L154

It doesn't appear that an [`imagePullSecrets`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core) stanza is added to the container in the catalog pod.  Is it possible that this is an oversight?

Am I misunderstanding the intent behind the `secrets` element in the CatalogSource custom resource?
