### ISSUE TITLE
OLM 0.14.2 ignores subscription channel changes.

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-lifecycle-manager#1510]
## Bug Report

**What did you do?**
I've created a multi-channel operator that uses the Automatic z-build strategy using a Catalog Index Image/Operator Bundle and CatalogSource.

- Channel V0.0 has CSV version 0.0.12
- Channel V1.0 has CSV 1.0.2 with a `olm.skipRange` of `>=1.0.0 <1.0.2`  

1.  Create a CatalogSource as follows:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: panamax-operators
  namespace: openshift-marketplace
spec:
  displayName: Panamax Operators
  image: quay.io/cdjohnson/ibm-sample-panamax-catalog@sha256:e467fdb339d9c24229041a99c5ea49cea1f373230077d68c3e121cd3c03eab95
  publisher: IBM
  sourceType: grpc
```
2.  Create a namespace: `panamax`
3.  Create a Subscription to the `V0.0` channel:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-sample-panamax
  namespace: panamax
spec:
  channel: V0.0
  installPlanApproval: Automatic
  name: ibm-sample-panamax
  source: panamax-operators
  sourceNamespace: openshift-marketplace
```
4.  Verify that the InstallPlan and CSV are properly installed.  I see:
```
NAME                         DISPLAY                VERSION   REPLACES   PHASE
ibm-sample-panamax.v0.0.12   IBM Panamax Operator   0.0.12               Succeeded
```

5.  Enable debug=true on the `operator-catalog` deployment
6.  Patch the subscription to channel: V1.0
    `oc patch sub ibm-sample-panamax -p '{"spec": {"channel": "V1.0"}}' --type merge`

**What did you expect to see?**
I'm expecting a new InstallPlan to be generated that will upgrade the CSV to the head version in the V1.0 channel.

**What did you see instead? Under which circumstances?**
I didn't see any change whatsoever.  From the logs:
```
$ oc -n openshift-operator-lifecycle-manager logs deploy/catalog-operator
time="2020-05-09T19:34:49Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/panamax/subscriptions/ibm-sample-panamax
time="2020-05-09T19:34:49Z" level=debug msg="reconciliation successful" event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/panamax/subscriptions/ibm-sample-panamax state="*subscription.catalogHealthyState"
time="2020-05-09T19:34:49Z" level=debug msg="resolving sources" id=3B1Xa namespace=panamax
time="2020-05-09T19:34:49Z" level=debug msg="checking if subscriptions need update" id=3B1Xa namespace=panamax
time="2020-05-09T19:34:49Z" level=debug msg="resolving subscriptions in namespace" id=3B1Xa namespace=panamax
```

**Environment**
* operator-lifecycle-manager version:
Using OpenShift 4.4.3 that uses OLM 0.14.2.

* Kubernetes version information:
```
Client Version: openshift-clients-4.4.0-202003060720
Server Version: 4.4.3
Kubernetes Version: v1.17.1
```
* Kubernetes cluster kind: 
OpenShift UPI on amd64 coreos.

**Possible Solution**

**Additional context**

This is what the (abbreviated) PackageManifest looks like for my catalog:
```
status:
  catalogSource: panamax-operators
  catalogSourceDisplayName: Panamax Operators
  catalogSourceNamespace: openshift-marketplace
  catalogSourcePublisher: IBM
  channels:
  - currentCSV: ibm-sample-panamax.v0.0.12
    currentCSVDesc:
      annotations: 
       capabilities: Basic Install
      version: 0.0.12
    name: V0.0
  - currentCSV: ibm-sample-panamax.v1.0.1
    currentCSVDesc:
      annotations:
        capabilities: Basic Install
        olm.skiprange: '>=1.0.0 <1.0.1'
      version: 1.0.1
    name: V1.0
```
