### ISSUE TITLE
Unable to fetch operator from OperatorSource on k8 cluster?

### ISSUE THREAD

**Issue by rvsingh011** [operator-framework/operator-lifecycle-manager#1530]
## why I am unable to fetch operators from the operator source on k8 cluster?

**What did you do?**
I added this as operatorSource to the cluster. 
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: redhat-operators
  namespace: default
spec:
  displayName: Red Hat Operators
  endpoint: 'https://quay.io/cnr'
  publisher: Red Hat
  registryNamespace: redhat-operators
  type: appregistry
```

then, As per the documentation, I added a catalog source 
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    olm-visibility: hidden
    openshift-marketplace: 'true'
    opsrc-datastore: 'true'
    opsrc-owner-name: redhat-operators
    opsrc-owner-namespace: default
    opsrc-provider: redhat
  name: redhat-operators
  namespace: default
spec:
  address: 'redhat-operators.openshift-marketplace.svc:50051'
  displayName: Red Hat Operators
  icon:
    base64data: ''
    mediatype: ''
  publisher: Red Hat
  sourceType: grpc
```

**What did you expect to see?**
I should see the operators, and doing 
`kubectl get opsrc`
I should see the `Status` as `Succeeded`. 

**What did you see instead? Under which circumstances?**
I don't see anything under `Status`
![image](https://user-images.githubusercontent.com/17317582/82364791-5f390680-9a2d-11ea-9139-9389d0258e1b.png)

**Environment**
OLM version : 0.14.1

* Kubernetes version information:
```json
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"e6f1cd7", GitTreeState:"clean", BuildDate:"2020-04-20T06:30:19Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
  

* Kubernetes cluster kind: minikube

**Additional context**
Output of 
```kubectl describe opsrc redhat-operators```
```
Name:         redhat-operators
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"operators.coreos.com/v1","kind":"OperatorSource","metadata":{"annotations":{},"name":"redhat-operators","namespace":"defaul...
API Version:  operators.coreos.com/v1
Kind:         OperatorSource
Metadata:
  Creation Timestamp:  2020-05-19T16:28:33Z
  Generation:          1
  Managed Fields:
    API Version:  operators.coreos.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:displayName:
        f:endpoint:
        f:publisher:
        f:registryNamespace:
        f:type:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-05-19T16:28:33Z
  Resource Version:  235166
  Self Link:         /apis/operators.coreos.com/v1/namespaces/default/operatorsources/redhat-operators
  UID:               c398bdfe-ba9b-4730-baf3-82cd7247dc4b
Spec:
  Display Name:        Red Hat Operators
  Endpoint:            https://quay.io/cnr
  Publisher:           Red Hat
  Registry Namespace:  redhat-operators
  Type:                appregistry
Events:                <none>```
