### ISSUE TITLE
secret does not work with catalogsource

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1536]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-catalog
  namespace: default
spec:
  name: my-catalog
  sourceType: grpc
  image: <your catalog image>
  secrets:
  - my-pull-secret
```

I found the secrets does not work for my cluster, please checkout https://github.com/operator-framework/operator-lifecycle-manager/issues/1294#issuecomment-625570581 for detail.

FYI @hassenius @sethpeterson @jeyaramashok 

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
