### ISSUE TITLE
Where to see the "MANUAL" approvals for operators in k8 clusters? 

### ISSUE THREAD

**Issue by rvsingh011** [operator-framework/operator-lifecycle-manager#1546]
## Question

**What did you do?**
I am working on a k8 cluster that has an OLM installed. I am trying to install an operator from the package manifest. 
1. I ran the command 
`kubectl -n olm get packagemanifests`
2. selected cockroach DB for installation.
3. I am replicating the steps that we do in the openshift console. I generated  a subscription file for that operator and it looks something like this 

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-cockroachdb
  namespace: operators
spec:
  channel: stable
  name: cockroachdb
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Manual
```
4. Applied the file to the cluster.
5. Operator came up and working fine. 

**What did you expect to see?**
I do not have an OKD attached to the k8 cluster. Now if there is a new version of the operator available how can I track that? Is there a command which can be used to see all the remaining approvals? On OKD and console we can see. It will be really helpful if you can point me to the code where this happens. 

**Environment**

K8 cluster : ```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}```

OLM version: 0.14.1
