### ISSUE TITLE
can olm add retry mechanism when installing operator failed

### ISSUE THREAD

**Issue by yahliu** [operator-framework/operator-lifecycle-manager#1565]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I hit one problem that installed operator failed due to environment unstable(maybe ectd server not stable) in that period in OCP4.3.13. so the operator status always "Pending".  checked the installplan, already reported failed. 
```
conditions:
  - lastTransitionTime: "2020-06-03T08:59:15Z"
    lastUpdateTime: "2020-06-03T08:59:15Z"
    message: 'error creating clusterrole monitoring-prometheus-operator-ext.v1.9.1-8x6rn:
      etcdserver: request timed out'
    reason: InstallComponentFailed
    status: "False"
    type: Installed
  phase: Failed
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Hope can add retry mechanism when one operator install failed.  5 times or 10 times ...
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

The operator still always Pending status.

**Environment**
* operator-lifecycle-manager version: `quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6d678859d3e67f523e1b1153fb6810c362ef85302c4a49fd08ecc0770d274fe4`

* Kubernetes version information: v1.16.2

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
