### ISSUE TITLE
How to get the namespace where the operator is being installed

### ISSUE THREAD

**Issue by yersan** [operator-framework/operator-lifecycle-manager#1575]
## Type of question

General context and help around the operator-sdk

## Question

**What did you do?**
I am installing an Operator by using OLM. The `CustomResourceDefinition` defines a conversion webhook with the following configuration:

```yaml
conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1alpha1","v1alpha2"]
      clientConfig:
        service:
          namespace: webhook-service-ns
          name: webhook-name
          path: /convert
          port: 443
```

The `clientConfig` section defines the service that acts as proxy to access to the Webhook registered in the operator.

When I am installing the operator manually without using OLM, I can create the webhook service resource first:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: operator-conversion-webhook
  labels:
    app: operator-app
spec:
  ports:
    - port: 443
  selector:
    app: operator-app
```

This service doesn't have a namespace defined, so it will get the current namespace I am working on when it is created.

Then I have to manually modify my CRD and configure the current service namespace into the `clientConfig` section and create it.

My scenario requires that the Webhook service and the operator are in the same namespace, however, I don't know how I can achieve it when the operator is being installed via OLM, because:

1. clientConfig/service/namespace is mandatory and cannot be empty.
2. I don't know which namespace the user is going to install the Operator and it looks like it is not possible to use something like a variable to get the current namespace when the resource is being created.

How can I configure the bundles for my operator so the clientConfig/service/namespace gets the namespace name where this operator is being installed? Is there any alternative? Is not possible?

**Environment**
* operator-lifecycle-manager version:
operator-sdk version: "v0.17.1", commit: "6d108056f39fa19546cf9235fad6e84b0683114a"

* Kubernetes version information:
OpenShift version: 4.4.5

Thanks !
