### ISSUE TITLE
The required operator from ClusterServiceVersion isn't installed from the default channel.

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1612]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I want to install two customized operators. One of them requires another one.

I set the following `customresourcedefinitions:` in the `CSV`:

```
  customresourcedefinitions:
    owned:
      - description: PlatformNavigator is the Schema for the platformnavigators API
        displayName: Platform Navigator
        kind: PlatformNavigator
        name: platformnavigators.integration.ibm.com
        resources:
          - kind: Client
            name: ''
            version: oidc.security.ibm.com/v1
          - kind: ClusterRole
            name: ''
            version: v1
          - kind: ClusterRoleBinding
            name: ''
            version: v1
          - kind: Deployment
            name: ''
            version: v1
          - kind: Route
            name: ''
            version: route.openshift.io/v1
          - kind: Secret
            name: ''
            version: v1
          - kind: Service
            name: ''
            version: v1
          - kind: ServiceAccount
            name: ''
            version: v1
        statusDescriptors:
          - displayName: Status
            path: 'conditions[0].type'
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:status'
          - displayName: Platform Navigator UI
            path: 'endpoints[0].uri'
            x-descriptors:
              - 'urn:alm:descriptor:org.w3:link'
          - displayName: Reconciled Version
            path: versions.reconciled
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:reconciledVersion'
        version: v1beta1
    required:
      - description: CommonService is the Schema for the commonservices API
        displayName: CommonService
        kind: CommonService
        name: commonservices.operator.ibm.com
        version: v3
```

The required operator has three channels, `stable-v1`, `beta` and `dev`. and the `stable-v1` is the default channel.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I expect when an operator is required, it should be installed by the default channel `stable-v1` or the user can choose which channel would be used instead of using a random channel (maybe based on the alphabet order?).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I see the CSV from the `dev` channel is deployed.

**Environment**
* operator-lifecycle-manager version:
4.4.9

* Kubernetes version information:

➜  ~ kubectl version                                                                                                         
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+912792b", GitCommit:"912792b", GitTreeState:"clean", BuildDate:"2020-06-16T03:51:52Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
OCP

**Possible Solution**

**Additional context**

It works as expected using the default channel in OCP 4.3 and OCP 4.4.6
