### ISSUE TITLE
Support ConsoleYamlSample in bundle manifests

### ISSUE THREAD

**Issue by Jamstah** [operator-framework/operator-lifecycle-manager#1615]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to add `ConsoleYamlSample`s to my operator, but at the moment, I have to run an init hook in my operator pod to install them into the cluster

**Describe the solution you'd like**
Be able to drop `ConsoleYamlSample`s into the bundle `manifests` directory and have them applied to the cluster.

I did try this, and get `UnsupportedResource` on the InstallPlan
```yaml
    - resolving: ibm-integration-platform-navigator.v4.0.1
      resource:
        group: console.openshift.io
        kind: ConsoleYAMLSample
        manifest: >
          {"apiVersion":"console.openshift.io/v1","kind":"ConsoleYAMLSample","metadata":{"name":"pn-sample-1"},"spec":{"description":"PN
          Sample","snippet":false,"targetResource":{"apiVersion":"integration.ibm.com/v1beta1","kind":"PlatformNavigator"},"title":"Sample
          1","yaml":"---\napiVersion: integration.ibm.com/v1beta1\nkind:
          PlatformNavigator\nmetadata:\n    name: cp4i-navigator\n    namespace:
          cp4i\nspec:\n    license:\n        accept: true\n    mqDashboard:
          true\n    replicas: 3\n    version: 2020.2.1\n"}}
        name: pn-sample-1
        sourceName: pn
        sourceNamespace: openshift-marketplace
        version: v1
      status: UnsupportedResource
```
