### ISSUE TITLE
Metrics not following Prometheus best practices

### ISSUE THREAD

**Issue by dgrisonnet** [operator-framework/operator-lifecycle-manager#1627]
## Bug Report

**What did you do?**

I ran [promlint](https://godoc.org/github.com/prometheus/client_golang/prometheus/testutil/promlint) accross all metrics exposed in OpenShift and noticed that some metrics from OLM were not following Prometheus [best practices](https://prometheus.io/docs/practices/naming/).

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

The following OLM metrics were reported by promlint:

```yaml
catalog_source_count:
  - non-histogram and non-summary metrics should not have "_count" suffix
install_plan_count:
  - non-histogram and non-summary metrics should not have "_count" suffix
subscription_count:
  - non-histogram and non-summary metrics should not have "_count" suffix
csv_count:
  - non-histogram and non-summary metrics should not have "_count" suffix
csv_upgrade_count:
  - non-histogram and non-summary metrics should not have "_count" suffix
  - counter metrics should have "_total" suffix
```

**Environment**
* operator-lifecycle-manager version: master

**Possible Solution**

The reported metrics should be renamed in order to follow the best practices.

##### Gauge

Gauge metrics should not have a "_count" suffix as it is reserved for histograms and summaries. Instead of that, we tend to suffix the plural of the measured data. Thus, I would suggest the following changes:

[catalog_source_count](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/metrics/metrics.go#L134-L139) --> catalog_sources
[install_plan_count](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/metrics/metrics.go#L120-L125) --> install_plans
[subscription_count](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/metrics/metrics.go#L127-L132) --> subscriptions
[csv_count](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/metrics/metrics.go#L113-L118) --> cluster_service_versions

##### Counter

As promlint reported, counter metrics should have a "_total" suffix

[csv_upgrade_count](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/metrics/metrics.go#L142-L147) --> cluster_service_version_upgrades_total
