### ISSUE TITLE
Security concern OLM ClusterRole has significant cluster privileges

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1685]
## Bug Report

The OLM operator pod has significant cluster privileges that could lead to privileged escalation. In particular, the pod has access to all resource. As a result, hacking the pod provides an easy path to privileged escalation.

```
# Source: original/0000_50_olm_01-olm-operator.serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:controller:operator-lifecycle-manager
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
```

**What did you do?**
Review the OLM ClusterRoles for security

**What did you expect to see?**

A smaller scope of resources and verbs allowed in the OLM ClusterRole.

**What did you see instead? Under which circumstances?**

All resources and verbs are allowed.

**Environment**
* operator-lifecycle-manager version: 0.15.1

* Kubernetes version information:  n/a

* Kubernetes cluster kind: 

**Possible Solution**

Change ClusterRole to only include resources and verbs that are actually needed.

**Additional context**
