### ISSUE TITLE
OLM 0.16.1 fails to handle package semver dependencies.

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-lifecycle-manager#1770]
## Bug Report
The operator-registry project added the ability to model semver dependencies via the operator bundle dependencies.yaml, yet the latest version of OLM (0.16.1) does not appear to be able to consume these dependencies.

**What did you do?**
1.  Installed OCP 4.6 nightly build 9/17/2020 which has OLM 0.16.1.
2.  Created a catalog index image with the following operator bundle taxonomy

| Package  | Version | Channel | replaces | olm.skipRange | olm.package |
|-|-|-|-|-|-|
| testoperatora | 1.0.0 | v1.0 | none | none | none |
| testoperatorb | 4.0.0 | v4.0 | none | none  | testoperatora: <1.3 |

The dependency.yaml for b 4.0.0 is:
```
dependencies:
  - type: olm.package
    packageName: testoperatora
    version: "<1.3"
```

2.  Created the catalog source

```
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: depcatalogs
  namespace: openshift-marketplace
spec:
  displayName: "depcatalogs-semver-dep-nowork Operators"
  image: docker.io/cdjohnson/depcatalogs@sha256:40474c14d6aef2c0ca0fa5a12ee0d774430b3cec7afab9638ce6ac03aa2671ca
  publisher: IBM
  sourceType: grpc
EOF
```
3.  Create namespace `deptest`
4.  Create a own-namespace operator group

```
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - deptest
EOF
```
4.  Create a subscription for operator b that has a dependency on A via the dependency.yaml

```
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: testoperatorb
spec:
  source: depcatalogs
  sourceNamespace: openshift-marketplace

  channel: v4.0
  installPlanApproval: Automatic
  name: testoperatorb
  startingCSV: testoperatorb.v4.0.0
EOF
```

**What did you expect to see?**
I expected both operators A and B to be installed.

**What did you see instead? Under which circumstances?**
Operator B was installed, but not A.

**Environment**
* operator-lifecycle-manager version:

0.16.1
* Kubernetes version information:
Client Version: 4.6.0-0.nightly-2020-09-15-112431
Server Version: 4.6.0-0.nightly-2020-09-17-073141
Kubernetes Version: v1.19.0+b4ffb45

* Kubernetes cluster kind: 
OCP on aws

**Possible Solution**
None

**Additional context**

**Comment by cdjohnson** [comment]
I found I had a few user errors.

1.  The file was named incorrectly.  I had `dependency.yaml`, but the real name is `dependencies.yaml`
    - The `opm registry add` tool did log this in the debug messages as not detected, but I missed that.
2. The format of the `dependencies.yaml` for `type: olm.package` is incorrect in the [OCP documentation](https://docs.openshift.com/container-platform/4.5/operators/olm-packaging-format.html)

Instead of:
```
dependencies:
  - type: olm.package
    packageName: testoperatora
    version: "<1.3"
```
it should be:
```
dependencies:
  - type: olm.package
    value: 
      packageName: testoperatora
      version: "<1.3"
```
There is no error detected in OPM nor OLM with this invalid format.

3.  I was using the wrong range syntax.  The blang implementation requires all three parts, unlike the masterminds version, which I'm more used-to.   The `catalog-operator` debug logs showed this, but not the opm client.

So, the final, working version:
```
dependencies.yaml
dependencies:
  - type: olm.package
    value: 
      packageName: testoperatora
      version: "<1.3.0"
```

**Summary:**
1. Documentation error in the OCP documentation (schema error)
2. Lack of error handling in OLM (misnamed file, schema error)
3. Lack of error handling in OPM (misnamed file, schema error, semver range format)
