### ISSUE TITLE
Optional error description field to show the error custom error message when an operator installation fails

### ISSUE THREAD

**Issue by sruthakeerthikotla** [operator-framework/operator-lifecycle-manager#1814]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have an operator that depends on an another operator from a different catalog source. In a scenario where the other catalog source is not installed, the operator installation is stuck in an "Upgrade Pending" state without any clue on why the operator installation is not being completed

**Describe the solution you'd like**
It would be nice to give an optional field in the CSV to provide a custom error message at different important steps in the installation process that could be displayed to the end user like in the picture below. As an example in our scenario, the required CRD definition in the CSV could have a field for the error description like : 

```
 customresourcedefinitions:
    owned:
    - description: my CRD is amazing
      displayName: mycrd
      kind: sample
      name: crdsample
      version: v1
      errorDescription: Installation of myCRD failed. Verify that you have installed catalog source X.
```
And if at this point the installation fails, the content of the "errorDescription" can be shown like in the picture below or at least logged as an event that shows up in the cluster "Events".

<img width="974" alt="Screenshot 2020-10-15" src="https://user-images.githubusercontent.com/21327252/96163901-1a5fc000-0f38-11eb-8270-123d98302e3c.png">
