### ISSUE TITLE
Consumption of an operator from Operatorhub.io Catalog behind Proxy

### ISSUE THREAD

**Issue by yeplaa** [operator-framework/operator-lifecycle-manager#1845]
## Question

**What did you do?**

From a Kubernetes native without direct access to web, i have deployed OLM. I used my docker Registry Proxy (Ie Artifactory) to access to quay.io registry (for OLM images). It works.

But, when i want deploy an Operator from OperatorHub.io Catalog, the pull of image Operator (ie elastic for example) is KO because i don't access directly to quay.io registry and I would like to avoid repackaging all operators with my docker registry proxy.

**What did you expect to see?**

I have a proxy and i would like to be able to install the operators by pulling the images by this proxy.
I try to integrate my Proxy configuration in the subscription declaration but without success : 

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eck
spec:
  config:
    env:
    - name: HTTP_PROXY
      value: http://cntlm:3128
    - name: http_proxy
      value: http://cntlm:3128
    - name: HTTPS_PROXY
      value: http://cntlm:3128
    - name: https_proxy
      value: http://cntlm:3128
    #- name: NO_PROXY
    #  value: test
  channel: stable
  installPlanApproval: Automatic
  name: elastic-cloud-eck
  source: operatorhubio-catalog
  sourceNamespace: catalog-operator
  startingCSV: elastic-cloud-eck.v1.2.1
```

Also, i try to integrate Proxy configuration into Deployment Catalog-operator (from OLM Namespace), but it doesn't seem taken into account.

Have you an idea? 

Thanks

**Environment**
* operator-lifecycle-manager version: 0.16.1

* Kubernetes version information: 1.18
