### ISSUE TITLE
InstallPlan approval is Manual when create subscription with Automatic Approval Strategy

### ISSUE THREAD

**Issue by DanielXLee** [operator-framework/operator-lifecycle-manager#1859]
## Bug Report

**What did you do?**
1. Install etcd operator with Manual Approval Strategy in namespace `default`

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: default
spec:
  channel: singlenamespace-alpha
  installPlanApproval: Manual
  name: etcd
  source: community-operators
  sourceNamespace: openshift-marketplace
```

2. Install  jenkins-operator with Automatic Approval Strategy in namespace `default`

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins-operator
  namespace: default
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: jenkins-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```

But I found the `InstallPlan` `install-wchdm` for jenkins-operator approval is Manual
```bash
# oc get ip -n default
NAME            CSV                      APPROVAL   APPROVED
install-mvwsg   etcdoperator.v0.9.4      Manual     true
install-wchdm   jenkins-operator.0.6.0   Manual     false
```

**What did you expect to see?**
I want to see InstallPlan `install-wchdm` for jenkins-operator approval is Automatic

**What did you see instead? Under which circumstances?**
Test result is Manual.

I don't know if this is design or issue.

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:
```bash
oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.1     True        False         127m    Cluster version is 4.6.1
```

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
