### ISSUE TITLE
OLM 0.17.0 subscription behaves differently than 0.13.0

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-lifecycle-manager#1869]
We use an internal OCI registry in a disconnected Kubernetes cluster to serve some OCI images.

Therefore, when we subscribe to various community operators, we use the `spec.config.env` feature of the `Subscription` to set environment variables that cause the deployment generated by OLM from the subscription to use the OCI image refs from the subscription, rather than the OCI image refs hard-coded into the subscribed CSV. Example for subscribing to `https://operatorhub.io/operator/postgresql`:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgres-operator
  namespace: myns
spec:
  channel: stable
  installPlanApproval: Automatic
  name: postgresql
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    env:
    - name: RELATED_IMAGE_CRUNCHY_POSTGRES_HA
      value: internal-registry.mycluster.my.co/images/crunchy-postgres-ha:ubi7-9.6.19-4.5.0
    # there are many more in our subscription but this will surface the error
```

In olm 0.13.0, this subscription results in a `postgres-operator` deployment with a pod template specifying four containers, and in each container, the RELATED_IMAGE_CRUNCHY_POSTGRES_HA environment variable picks up the replacement image ref from the subscription. All good.

In olm 0.17.0, the `postgres-operator` deployment pod template has two of the containers correctly patched from the subscription, and two that have the unpatched image refs from the CSV.

As additional information, the cluster with olm 0.17.0 that fails is Kubernetes 1.18.9. The cluster with olm 0.13.0 that succeeds is OpenShift 3.11.272/Kubernetes 1.11.0.

However, this seems more likely to be OLM-related though - at present - I have not traced the code to verify that.

I should add that the negative effect of this (the actual problem) is that the postgres operator is unable to create the database cluster because the image refs is is using haven't been patched to ref the internal OCI registry.

Some more info: The postgres CSV has four containers - two of which define this ENV var and two that don't. It looks like the olm operator regression is - it is adding the ENV var from the subscription into the deployment container if it does not exist in the CSV container spec, but failing to patch the ENV in the deployment container if the ENV is defined in the CSV container spec.
