### ISSUE TITLE
User Input to the installed CSV in OLM

### ISSUE THREAD

**Issue by prafull01** [operator-framework/operator-lifecycle-manager#1908]
## Question

**What did you do?**
Currently, to install our operator through CSV we don't have any way to provide user input to the CSV.. The only way to add environment variable is:

```
config:
    env:
    - name: RESTORE_NAMESPACES
      value: RESTORE_NS
```

But not all things can be accepted through environment variables, like we want to set the memory and resource requirement based on the user's input. Is there any other way to take input from the user for OLM based operator.

If Not, Is this a feature planned in future for the OLM.

/kind support
