### ISSUE TITLE
Operator deployment resources claimed in CSV aren't passed into the operator deployment

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1940]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I try to deploy an Operator into the Openshift cluster. After the operator is deployed, I found the `.spec.containers[].resources` claimed in the `csv.spec.install.deployments` are not added in the operator deployment.
 
For example,
CSV:
```
  install:
    spec:
      deployments:
       ...
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 200m
                    memory: 256Mi
```
Deployment:
```
    spec:
    ...
      containers:
       ...
        - resources: {}
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I expect the deployment `resources` added into the CSV can be added into operator deployment during the installation.
 
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

The resources field is empty in the operator deployment. 

**Environment**
* operator-lifecycle-manager version:
0.15.1

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+ca4017d", GitCommit:"ca4017d", GitTreeState:"clean", BuildDate:"2020-11-14T01:37:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
OCP
**Possible Solution**

**Additional context**
