### ISSUE TITLE
Subscription config doesn't support env `valueFrom`

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1946]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

When I add a valueFrom in the subscription config, 
```
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: operand-deployment-lifecycle-manager-app
      spec:
        channel: beta
        installPlanApproval: Automatic
        name: ibm-odlm
        source: opencloud-operators
        sourceNamespace: openshift-marketplace
        config:
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: namespace-scope
                key: namespaces
```

The env wouldn't be copied into the deployment. It shows like

```
          env:
            - name: WATCH_NAMESPACE
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I expect the env variables could be copied completed.
 
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

It only has value when using valueFrom.

**Environment**
* operator-lifecycle-manager version:
0.15.1

* Kubernetes version information:
v1.18.3

* Kubernetes cluster kind: 
OCP
**Possible Solution**

```
	for _, newEnvVar := range newEnvVars {
		existing, found := findEnvVar(containerEnvVars, newEnvVar.Name)
		if found {
			existing.Value = newEnvVar.Value
			continue
		}

		merged = append(merged, corev1.EnvVar{
			Name:  newEnvVar.Name,
			Value: newEnvVar.Value,
		})
	}
```

In the inject.go, it only copied the value and ignore the ValueFrom.

**Additional context**
