### ISSUE TITLE
[Feature] Configure environment variables on Openshift console

### ISSUE THREAD

**Issue by cuttingedge1109** [operator-framework/operator-lifecycle-manager#2074]
## Feature Request
I have an issue when deploying the operators which require configuration for environment variable on Openshift console.
When I define the subscription declaratively and apply it using `oc` CLI, I can configure Env vars like this:
```
  config:
    env:
    - name: ARGS
      value: "-v=10"
```

Is it impossible to do the same config on UI?
