### ISSUE TITLE
Does OLM automatically convert deprecated APIs

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-lifecycle-manager#2132]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

General question. Is it OLM that is automatically converting deprecated APIs to the new version? Or is OCP doing this?

## Question

**What did you do?**
Created a CRD using v1beta1 API. Snippet of important section:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # annotations:
  #   "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  name: certificates.certmanager.k8s.io
```

**What did you expect to see?**
`oc get crd certificates.certmanager.k8s.io` should return same output as above snippet

**What did you see instead? Under which circumstances?**
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
```

**Environment**
* operator-lifecycle-manager version:

OCP version: 4.6.16

* Kubernetes version information:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+e49167a", GitCommit:"e49167aad6a08046be6ab21ff13029110c76951d", GitTreeState:"clean", BuildDate:"2021-01-28T07:35:27Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
  

* Kubernetes cluster kind:

**Additional context**

I checked the status of the CRD I created, and I see the an error message:
```yaml
status:
  conditions:
    - type: NamesAccepted
      status: 'True'
      lastTransitionTime: '2021-04-30T18:43:39Z'
      reason: NoConflicts
      message: no conflicts found
    - type: Established
      status: 'True'
      lastTransitionTime: '2021-04-30T18:43:39Z'
      reason: InitialNamesAccepted
      message: the initial names have been accepted
    - type: KubernetesAPIApprovalPolicyConformant
      status: 'False'
      lastTransitionTime: '2021-04-30T18:43:39Z'
      reason: MissingAnnotation
      message: >-
        protected groups must have approval annotation
        "api-approved.kubernetes.io", see
        https://github.com/kubernetes/enhancements/pull/1111
```
but the CRD works fine, as I am able to create the resource it provides.

I know that the v1 CRD API `apiextensions.k8s.io/v1` does not allow for CRDs to have `k8s.io` in the API Group, so if I were to try to create
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
```
with `oc apply`, I would receive the following error:
```console
The CustomResourceDefinition "certificates.certmanager.k8s.io" is invalid: 
* spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
* metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
```

My other question is, how did the `apiextensions.k8s.io/v1beta1` API get converted by OLM or OCP? Aside from the status showing an error message, everything is running fine.
