### ISSUE TITLE
Backport fix of targetPort in webhookConfig of CSV

### ISSUE THREAD

**Issue by prafull01** [operator-framework/operator-lifecycle-manager#2174]
## Bug Report

**What did you do?**
Deployed the operator with webhook config which has `containerPort (443)` and `targetPort (9443)` different.

**What did you expect to see?**
I expect to see the webhook service which have different container and target port
```
ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 9443   // target port coming right
```

**What did you see instead? Under which circumstances?**
On OCP 4.5.39, I have seen that the targetPort is `443` only.
```
ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 443
```

This issue has been fixed with following [commit](https://github.com/operator-framework/api/commit/f83191c79b2caf1be37d13773e8d8981fd56b8f4#diff-bea9d74b98325f6f4a69e80fb69a30afc14b00dc2b45fbcb24160bdc08cbe1c5) 

**Environment**
Openshift 4.5.39

**Possible Solution**

**Additional context**
Backport the above fix to Openshift release 4.5
