### ISSUE TITLE
Support mark default version for CRD with multiple versions

### ISSUE THREAD

**Issue by tossmilestone** [operator-framework/operator-lifecycle-manager#2185]
## Feature Request
Support mark default version for CRD with multiple versions. 

If an operator owns a CRD with multiple versions, the csv will have the CRD kind with different versions. It will cause users could not determin which CRD version to use, missing the storage version defined in the CRD object.

The OLM should enable marking which CRD version is the storage version, then the user could use the CRD vesion as default
version to create the CRs.

**Is your feature request related to a problem? Please describe.**
Example: I have an CRD `MySQLCluster`, it has versions `v1alpha`, `v1beta` and `v1`. The storage version is `v1`.
The csv file will have 3 `MySQLCluster` definitions as follows:
```yaml
...
  customresourcedefinitions:
    owned:
      - description: Instance of a MySQL Cluster
        displayName: MySQL Custer
        kind: MySQLCluster
        name: mysqlclusters.example.com
        version: v1
      - description: Instance of a MySQL Cluster
        displayName: MySQL Custer
        kind: MySQLCluster
        name: mysqlclusters.example.com
        version: v1alpha
      - description: Instance of a MySQL Cluster
        displayName: MySQL Custer
        kind: MySQLCluster
        name: mysqlclusters.example.com
        version: v1beta
...
```
The user don't know which version is the preferred `MySQLCluster` version, and will be confused on such versions.

**Describe the solution you'd like**
Add a field in `CRDDescription` to describe if the CRD is the default, and validate the field if there are multiple CRD versions of one kind.
