### ISSUE TITLE
SA ownreference isn't updated during the operator upgrade

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#2193]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

We upgrade operators by switching the catalog source image.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

We expect all the operators are upgraded successfully to the `succeeded` status.
 
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Several new operators are in pending status. These operators can't be upgraded to the later version.

In the CSV status, it shows service account is owned by another ClusterServiceVersion

```
      name: ibmlicensings.operator.ibm.com
      status: Present
      uuid: 5db2e0ca-29fb-49df-977a-6343129a271b
      version: v1
    - group: ''
      kind: ServiceAccount
      message: Service account is owned by another ClusterServiceVersion
      name: ibm-licensing-operator
      status: PresentNotSatisfied
      version: v1
    - group: ''
      kind: ServiceAccount
      message: Service account is owned by another ClusterServiceVersion
      name: ibm-license-service
      status: PresentNotSatisfied
      version: v1
```

The install plan of the operator has been completed, but the service account still references the old CSV.

**Environment**
* operator-lifecycle-manager version:

0.17.0

* Kubernetes version information:

      name: kube-apiserver
      version: 1.20.0-beta.2

* Kubernetes cluster kind: 

OCP 4.7.13

**Possible Solution**

Delete and reinstall these operators

**Additional context**

I am wondering if it is because the owner reference of the service account isn't updated during the update in OLM 0.17.0 
https://github.com/operator-framework/operator-lifecycle-manager/blob/v0.17.0/pkg/controller/operators/catalog/step_ensurer.go#L138

I believe this PR is a fix to solve the issue: https://github.com/operator-framework/operator-lifecycle-manager/pull/2076

@benluddy Could you help to confirm that?

Could we get which OCP versions have this fix?

cc @pgodowski

**Comment by njhale** [comment]
The referenced patch has been included in OCP version `4.7.11`, according to the [errata](https://access.redhat.com/errata/RHBA-2021:1550).

Since you're experiencing this on `4.7.13`, I think we may still have an issue. Will attempt to replicate on master (under the operator-framework org).

**Comment by benluddy** [comment]
The v0.17.0 you're seeing is the upstream OLM version at the time OCP v4.7 diverged from upstream -- you can determine the commit digest using `oc adm release info --commits 4.7.13`, which includes the change from the linked PR (https://github.com/operator-framework/operator-lifecycle-manager/blob/df08e59d3168b3c657c97ec45c5aebcbc9109f71/pkg/controller/operators/catalog/step_ensurer.go#L159).

Since you observed this on OpenShift, I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1974438 to track this downstream as well. Can you provide precise steps to reproduce there, please?

**Comment by horis233** [comment]
Since we don't know exactly about the root cause and this issue can't be reproduced on all the operators, we don't know how to reproduce the issue stably yet. However, we can see this issue happens very often. I am looking for some hits from code to see if I know the cause.

Also, I can provide some logs and YAML files I observed in the cluster to help us troubleshoot this issue.

I found a common symptom in the operators hit this issue. The same serviceaccount appears twice in the installplan.
```
    - resolving: operand-deployment-lifecycle-manager.v1.6.0
      resource:
        group: ''
        kind: ServiceAccount
        manifest: >-
          {"kind":"ConfigMap","name":"efed617aec34db68cb4c70a7315f92d51827a3d77f8ffc53b1e751f002b2f7c","namespace":"openshift-marketplace","catalogSourceName":"opencloud-operators","catalogSourceNamespace":"openshift-marketplace","replaces":"operand-deployment-lifecycle-manager.v1.5.1","properties":"{\"properties\":[{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandBindInfo\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandConfig\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandRegistry\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandRequest\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.package\",\"value\":{\"packageName\":\"ibm-odlm\",\"version\":\"1.6.0\"}}]}"}
        name: operand-deployment-lifecycle-manager
        sourceName: opencloud-operators
        sourceNamespace: openshift-marketplace
        version: v1
....
    - resolving: operand-deployment-lifecycle-manager.v1.6.0
      resource:
        group: ''
        kind: ServiceAccount
        manifest: >-
          {"kind":"ConfigMap","name":"efed617aec34db68cb4c70a7315f92d51827a3d77f8ffc53b1e751f002b2f7c","namespace":"openshift-marketplace","catalogSourceName":"opencloud-operators","catalogSourceNamespace":"openshift-marketplace","replaces":"operand-deployment-lifecycle-manager.v1.5.1","properties":"{\"properties\":[{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandBindInfo\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandConfig\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandRegistry\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.gvk\",\"value\":{\"group\":\"operator.ibm.com\",\"kind\":\"OperandRequest\",\"version\":\"v1alpha1\"}},{\"type\":\"olm.package\",\"value\":{\"packageName\":\"ibm-odlm\",\"version\":\"1.6.0\"}}]}"}
        name: operand-deployment-lifecycle-manager
        sourceName: opencloud-operators
        sourceNamespace: openshift-marketplace
        version: v1
      status: Present
```

<img width="1151" alt="Screen Shot 2021-06-23 at 11 47 06 AM" src="https://user-images.githubusercontent.com/33276414/123128130-e28b0f80-d418-11eb-8ddd-eccbd157ec59.png">

Operator looks like this in the openshift console:
<img width="1256" alt="Screen Shot 2021-06-23 at 11 48 27 AM" src="https://user-images.githubusercontent.com/33276414/123128255-fe8eb100-d418-11eb-8c85-5032b3a76889.png">


This happens when we upgrade an operator called `operand-deployment-lifecycle-manager`

I added these yaml files in it: previous CSV (1.5.1), upcoming CSV (1.6.0), installplan and subscription.
[operand-deployment-lifecycle-manager.zip](https://github.com/operator-framework/operator-lifecycle-manager/files/6703234/operand-deployment-lifecycle-manager.zip)
