### ISSUE TITLE
CatalogSource Pod Tolerations and Selector

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-lifecycle-manager#2452]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like CatalogSource pods to be allocated to specific nodes in my cluster through node selectors and tolerations.

**Describe the solution you'd like**
I'd like to be able to specify the node selectors and tolerations in a configuration section of the CatalogSource spec in a similar way as is done with `Subscription`

For example:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/operatorhubio/catalog:latest
  displayName: Community Operators
  publisher: OperatorHub.io
  config:
    nodeSelector:
        node-role.kubernetes.io/master: ""
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
      effect: "NoSchedule"
```

The downside here is that it makes the CatalogSource a bit of a leaky abstraction by floating these pod concerns to the top. If we decide on a podless implementation of the spec, these cease to make any sense. Having said that, if it were the case, the fields could just be ignored while they are being deprecated. Not nice, but doesn't get in the way of users.

**Comment by perdasilva** [comment]
I've started to work on these changes (https://github.com/operator-framework/api/pull/173). I've set the PR to WIP while we align on this thread.

**Comment by anik120** [comment]
>The downside here is that it makes the CatalogSource a bit of a leaky abstraction by floating these pod concerns to the top

We do this frequently with our APIs though. For example, the `spec.secrets` field is essentially a leaky abstraction which floats SA concerns to the top. So this is not something new we'll be doing at least. 

In fact, aren't all kube apis doing the same thing too? Pod "concerns" are also floated to Deployment, i.e you can specify taints and toleration in the Deployment for pods to adhere to.

**Comment by njhale** [comment]
> In fact, aren't all kube apis doing the same thing too? Pod "concerns" are also floated to Deployment, i.e you can specify taints and toleration in the Deployment for pods to adhere to.

`Deployments` **always** result in `Pods`, while`CatalogSources` may be implemented in other ways

**Comment by perdasilva** [comment]
Would injecting this information into the controller environment via the downward api be a possible solution?

**Comment by perdasilva** [comment]
@njhale just for my understanding, when we say union types, we mean something like accepting different structures for a particular attribute right? E.g. having the cross cutting attributes at the top level, then specific configurations for the different deployment options. For instance,

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: olm
spec:
  # sourceType: grpc # deprecated
  # image: quay.io/operatorhubio/catalog:latest # deprecated
  displayName: Community Operators
  publisher: OperatorHub.io
  source:
    grpc:
      image: quay.io/operatorhubio/catalog:latest
      nodeSelector:
          node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
        effect: "NoSchedule"
```

(I haven't looked into the spec enough to know if this is accurate, but I'm more wondering about the meaning behind union types in this context.)
