### ISSUE TITLE
Installing an operator in two different namespaces

### ISSUE THREAD

**Issue by vfrans** [operator-framework/operator-lifecycle-manager#2502]
## Type of question

Implementing feature and general help

## Question

**What did you do?**
I tried to install the keycloak operator twice in two separate namespaces to be able to segregate keycloak deployments per namespace.
I know that KC operator is single-namespace only:
```
k get packagemanifest keycloak-operator -o jsonpath="{.status.channels[0].currentCSVDesc.installModes}"
[
{"supported":true,"type":"OwnNamespace"},
{"supported":true,"type":"SingleNamespace"},
{"supported":false,"type":"MultiNamespace"},
{"supported":false,"type":"AllNamespaces"}
]
```
but I would expect to be able to install it on two different namespaces to provision resources in those two namespaces (as well as being able to test out new version of the operator in the dev namespace, etc...)

For this purpose, I create two OperatorGroup and two subscriptions.

For the *die* namespace:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-die-group
  namespace: die
spec:
  targetNamespaces:
    - die
```
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sub-to-kc-die
  namespace: die
spec:
  channel: alpha
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Manual
  startingCSV: 15.0.2
```
For the *bas* namespace:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-bas-group
  namespace: bas
spec:
  targetNamespaces:
    - bas
```
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sub-to-kc-bas
  namespace: bas
spec:
  channel: alpha
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Manual
  startingCSV: 15.0.2
```
I applied first the OG and SUB in the die namespace and it worked correctly (after approving the IP, ofc). I now have a keycloak-operator pod in the die namespace:
```
k get pods -n die
NAME                                 READY   STATUS    RESTARTS   AGE
keycloak-operator-5888b57c46-54dqt   1/1     Running   0          17h
```
```
k get ip -n die
NAME            CSV                         APPROVAL   APPROVED
install-ntp8q   keycloak-operator.v15.0.2   Manual     true
```
```
k get csv -n die
NAME                        DISPLAY             VERSION   REPLACES                    PHASE
keycloak-operator.v15.0.2   Keycloak Operator   15.0.2    keycloak-operator.v15.0.1   Succeeded
```

However, when I apply the manifests for the bas namespace, it does not work:
```
k get pods -n bas
No resources found in bas namespace.
```
```
k get ip -n bas
No resources found in bas namespace.
```
```
k get csv -n bas
No resources found in bas namespace.
```
```
k describe sub -n bas
Name:         sub-to-kc-bas
Namespace:    bas
Labels:       operators.coreos.com/keycloak-operator.bas=
Annotations:  <none>
API Version:  operators.coreos.com/v1alpha1
Kind:         Subscription
Metadata:
  Creation Timestamp:  2021-11-30T15:22:27Z
  Generation:          1
  Managed Fields:
    API Version:  operators.coreos.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:catalogHealth:
        f:conditions:
        f:lastUpdated:
    Manager:      catalog
    Operation:    Update
    Subresource:  status
    Time:         2021-11-30T15:22:27Z
    API Version:  operators.coreos.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:channel:
        f:installPlanApproval:
        f:name:
        f:source:
        f:sourceNamespace:
        f:startingCSV:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-11-30T15:22:27Z
    API Version:  operators.coreos.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:operators.coreos.com/keycloak-operator.bas:
    Manager:         olm
    Operation:       Update
    Time:            2021-11-30T15:22:27Z
  Resource Version:  1536335
  Self Link:         /apis/operators.coreos.com/v1alpha1/namespaces/bas/subscriptions/sub-to-kc-bas
  UID:               02a72674-d27d-43d9-b5b1-a6c29f05bcd5
Spec:
  Channel:                alpha
  Install Plan Approval:  Manual
  Name:                   keycloak-operator
  Source:                 operatorhubio-catalog
  Source Namespace:       olm
  Starting CSV:           15.0.2
Status:
  Catalog Health:
    Catalog Source Ref:
      API Version:       operators.coreos.com/v1alpha1
      Kind:              CatalogSource
      Name:              operatorhubio-catalog
      Namespace:         olm
      Resource Version:  1403563
      UID:               e469cacd-1812-4059-b423-9cb40e9b6ba0
    Healthy:             true
    Last Updated:        2021-11-30T15:27:07Z
  Conditions:
    Last Transition Time:  2021-11-30T15:27:07Z
    Message:               all available catalogsources are healthy
    Reason:                AllCatalogSourcesHealthy
    Status:                False
    Type:                  CatalogSourcesUnhealthy
    Message:               constraints not satisfiable: no operators found with name 15.0.2 in channel alpha of package keycloak-operator in the catalog referenced by subscription sub-to-kc-bas, subscription sub-to-kc-bas exists
    Reason:                ConstraintsNotSatisfiable
    Status:                True
    Type:                  ResolutionFailed
  Last Updated:            2021-12-01T09:17:25Z
Events:                    <none>
```

**What did you expect to see?**
I excepted to see the same behavior on the two different namespaces, having a second keycloak-operator deployed in the bas namespace.

**What did you see instead? Under which circumstances?**
Noting gets deployed in bas and there is the error that I don't quite understand on the OG of bas:
```
constraints not satisfiable: no operators found with name 15.0.2 in channel alpha of package keycloak-operator in the catalog referenced by subscription sub-to-kc-bas, subscription sub-to-kc-bas exists
```

**Environment**
* operator-lifecycle-manager version:
```
quay.io/operator-framework/olm@sha256:7df4e1f16bfd107acc76bc1e3a5910224b90b317aca697b6541c3e55c27bc2ee
```

* Kubernetes version information:

```
k version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:07:39Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:03:17Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
  

* Kubernetes cluster kind: 
MicroK8S cluster with 4 nodes

**Additional context**
Nothing relevant.

Thanks a lot in advance for you assistance
