### ISSUE TITLE
Reference to "cp" command in bundle_unpacker.go has wrong arch

### ISSUE THREAD

**Issue by devops-42** [operator-framework/operator-lifecycle-manager#2769]
ARCH: arm64
DISTRO: microk8s

Hi,

when deploying a new operator in k8s a job template is rendered containing initContainers. The first one issues a cp command:
```
         command:
            - /bin/cp
            - '-Rv'
            - /bin/cpb
            - /util/cpb
```

While the tooling itself is on the correct CPU architecture, the `cp` command is still on `amd64`. This breaks the operator installation. The affected file is most likely:

https://github.com/operator-framework/operator-lifecycle-manager/blob/5a7f8033dfc04150d1c21ef4e86fd7bc00bbfa39/pkg/controller/bundle/bundle_unpacker.go#L138

Any chance either to fix this? As a workaround the first `initContainer` could be dropped, the second one needs to be slightly modified:

```
        - name: pull
          image: >-
            quay.io/operatorhubio/grafana-operator@sha256:85a6c64273b3b4fe65e4937b300bf9fddd24a7f1ece7ff9b7de925c77669fc17
          command:
            - /bin/cpb
            - /bundle
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: bundle
              mountPath: /bundle
            - name: util
              mountPath: /util
```

Thanks for your help.
