### ISSUE TITLE
Can't delete operator

### ISSUE THREAD

**Issue by suikast42** [operator-framework/operator-lifecycle-manager#2807]
I am on the latest OLM version  0.21.2.

If I delete CSV and the Subscription I the operator pod is undeployed but I have an entry in the CRD section. 

1 .Create a chruncy data operarator
``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: test-og
  namespace: test
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql
  namespace: test
spec:
  channel: v5
  name: postgresql
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
  startingCSV: postgresoperator.v5.1.0
  config:
    nodeSelector:
      cloud.local/nodetype: "worker"
      cloud.local/stack-core: "true"
```

2. Delete the subscription
``` kubectl delete sub postgresql -n test```
3. Delete the ClusterSerivceVerion
 ``` kubectl  delete csv  postgresoperator.v5.1.1 -n test```

5.  ```kubectl   get operators```
 ```
NAME                      AGE
cert-manager.stack-core   46m
postgresql.test           12m
```

6.   
 ```kubectl delete operators postgresql.test```
 ```kubectl get operators ```
 ```
NAME                      AGE
cert-manager.stack-core   50m
postgresql.test           4s
```

So why is the resource postgresql.test  left and why I can't delete it ?
