### ISSUE TITLE
Automate an installPlan approval on first install while keeping the installPlanApproval setting to manual?

### ISSUE THREAD

**Issue by CoaxVex** [operator-framework/operator-lifecycle-manager#2855]
I'm looking for the best way to automate the deployment of an operator through OLM and objects that make use of it.
I'm currently using helm, but I believe I would have the same problem with flux or argo or with a flat yaml file.

Say I have the following subscription in my configuration:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-xtradb-cluster-operator
spec:
  channel: stable
  name: percona-xtradb-cluster-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: percona-xtradb-cluster-operator.v1.11.0
```
This results in an installPlan which I need to manually approve, before I can start creating custom resources:
```
oc get ip
NAME            CSV                                       APPROVAL    APPROVED
install-jgvhp   percona-xtradb-cluster-operator.v1.11.0   Manual      false
```

I'm not able to apply a generated yaml that includes both the subscription for the percona-xtradb-cluster-operator and an object that uses one of its CRD's like PerconaXtraDBCluster, because the CRD's don't exist yet.

```
oc apply -f percona.yml 
subscription.operators.coreos.com/percona-xtradb-cluster-operator created
error: unable to recognize "percona.yml": no matches for kind "PerconaXtraDBCluster" in version "pxc.percona.com/v1-12-0"
```

Helm has a pre-install hook that I could use to create the subscription before the other objects, but the chart will fail until I manually approve the install plan.

I was hoping that the install plan would be automatically approved (once) because I specified the startingCSV, but that doesn't seem to be the case.

Should I be creating my own installplan that has spec.approved set to true?

I'm running on OCP 4.9.32 and am using the bundled OLM.
