### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by danmillwood** [operator-framework/operator-lifecycle-manager#2861]
## Bug Report

**What did you do?**

I installed olm on linux/s390x and connected to a catalog of operators.
I then attempted to install an operator.  This resulted in an `InstallPlan` resource being created and a `Job` resource being created in the OLM namespace.

The job failed, and looking at the corresponding pod, I could see it failed to run an initContainer called `util`

```
kubectl logs 648e77c9a7adc015c096cf0e2667326e167263a93266a3c6f52b4a62adlgnf2 util -n olm
standard_init_linux.go:228: exec user process caused: exec format error
```

Googling for this error suggests that the image is for the wrong architecture, and this is where Im confused as to how this is happening.  From the pod yaml, this is the image its trying to retrieve:

```
  initContainers:
  - command:
    - /bin/cp
    - -Rv
    - /bin/cpb
    - /util/cpb
    image: quay.io/operator-framework/olm@sha256:2b4fee73c05069d9d2c537c7d3072241097914748abfb938b5b08c969b2f544b
    imagePullPolicy: IfNotPresent
    name: util
```

This appears to be exactly the same image, as is being run for the olm operator pod, which is running successfully.

```
  containers:
  - args:
    - --namespace
    - $(OPERATOR_NAMESPACE)
    - --writeStatusName
    - ""
    command:
    - /bin/olm
    env:
    - name: OPERATOR_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OPERATOR_NAME
      value: olm-operator
    image: quay.io/operator-framework/olm@sha256:2b4fee73c05069d9d2c537c7d3072241097914748abfb938b5b08c969b2f544b
    imagePullPolicy: IfNotPresent
```

```
kubectl get pods -n olm
NAME                                                              READY   STATUS       RESTARTS   AGE
648e77c9a7adc015c096cf0e2667326e167263a93266a3c6f52b4a62adlgnf2   0/1     Init:Error   0          2d1h
648e77c9a7adc015c096cf0e2667326e167263a93266a3c6f52b4a62admm8n6   0/1     Init:Error   0          2d1h
catalog-operator-8d9d97478-8v5mx                                  1/1     Running      0          6d21h
ibm-operator-catalog-x9gln                                        1/1     Running      0          2d2h
olm-operator-64b58958bb-pprtx                                     1/1     Running      0          21h
packageserver-545b4f5db8-nf42n                                    1/1     Running      0          6d23h
packageserver-545b4f5db8-pkp9h                                    1/1     Running      0          6d21h
```

So Im confused how an image can be running successfully in one container and failing when used in another container, unless that image really does have a binary in it for the wrong architecture?

**What did you expect to see?**

The job to execute to completion

**What did you see instead? Under which circumstances?**

The pod for the job failed at the first initContainer

**Environment**
* operator-lifecycle-manager version:

sha256:2b4fee73c05069d9d2c537c7d3072241097914748abfb938b5b08c969b2f544b
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/s390x"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:29:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/s390x"}
```

* Kubernetes cluster kind: 
Vanilla cluster with only 1 node (I had to add tolerations to various pods to get them to run on the control plane node)

**Possible Solution**

**Additional context**
