### ISSUE TITLE
Failed to deploy operator when API v1 is marked as unserved

### ISSUE THREAD

**Issue by tolusha** [operator-framework/operator-lifecycle-manager#2866]
## Bug Report

**What did you do?**
I have two version of my API `v1` and `v2`. 
I decided to mark v1 as unserved with `+kubebuilder:unservedversion` annotation and deployed operator on the cluster.

**What did you expect to see?**
Operator successfully installed.

**What did you see instead? Under which circumstances?**
Operator installation hang in a Pending state, csv status:
```yaml
  requirementStatus:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is not present
      name: checlusters.org.eclipse.che
      status: NotPresent
      version: v1
```

**Environment**
* operator-lifecycle-manager version:
OLM version: 0.19.0
git commit: 5cfc4d643f5fead6b02aa40a2a661b0fa64a2958

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+8471591", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-09-16T15:34:57Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
OpenShfit 4.10.0-0.nightly-2022-09-22-230013

**Possible Solution**

**Additional context**
