### ISSUE TITLE
Disable adopt-controller through feature-gates

### ISSUE THREAD

**Issue by aiyijing** [operator-framework/operator-lifecycle-manager#2916]
# adopt controller 
The adopt controller frequently updates operators.status of cluster scope resources. 
At the k8s level, this behavior generates a large number of audit events, and it 
also causes some pressure on etcd

**Comment by aiyijing** [comment]
I try to use feature-gates to disable it
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: olm-operator
spec:
  template:
    metadata:
      labels:
        app: olm-operator
    spec:
      containers:
          command:
          - /bin/olm
          args:
          - --feature-gates=OperatorLifecycleManagerV1=false
```
It cannot be started and has the following error log
``` bash
invalid argument "OperatorLifecycleManagerV1=false" for "--feature-gates" flag: cannot set feature gate OperatorLifecycleManagerV1 to false, feature is locked to true

```

Whether the adopt controller can be disabled, and whether other components in the olm depend on it.
