### ISSUE TITLE
OperatorGroups: I cannot use 2 depended operator in my operator which are conflicting about Supported InstallModes  (Keyclaok and mini operator)

### ISSUE THREAD

**Issue by merihilgor** [operator-framework/operator-lifecycle-manager#2927]
## Bug Report

 
Hi,
I am developing an operator and I want to deploy depended operators in separate namespaces. But Supported InstallModes are conflicting for some operators and I can not use them together. For example keycloak operator and minio operator. When I add both of them in my dependencies.yaml file; if I use single namespace with an OperatorGroup which is targeting single namespace; depended minio operator is failing and if I use multi namespace with an OperatorGroup which is targeting all namespaces keycloak operator is failing. I also tried to use matchLabels and staticProvidedAPIs but couldn't get it working.

**What did you do?**
developed an operator which have 
dependencies.yaml file:

```
- type: olm.gvk
  value:
    group: minio.min.io
    kind: Tenant
    version: v2
 - type: olm.gvk
  value:
    group: k8s.keycloak.org
    kind: Keycloak
    version: v2alpha1 
```

ClusterServiceVersion  failing with UnsupportedOperatorGroup

**What did you expect to see?**
Both depended operator ClusterServiceVersion shouldn't fail. Better I want to deploy all depended operator in separate namespace s so  I should be able to define target namespace in dependencies.yaml file so I can create separate OperatorGroup for each one.

**Environment**
* operator-lifecycle-manager version:

OLM version: v0.23.1
git commit: 6c564a670c94c50a9270bb5338a0e32a3e11496f

* Kubernetes version information:
k81-22

* Kubernetes cluster kind: 
* EKS

**Possible Solution**

**Additional context**
