### ISSUE TITLE
Duplicated ServiceAccount subjects in Namespace-scoped operator rolebindings

### ISSUE THREAD

**Issue by samuel-hawker** [operator-framework/operator-lifecycle-manager#2962]
## Bug Report

**What did you do?**
Hello all,  I was hoping to get some help with an issue I've been working on.
A user reported to us that the RBs created for our operator had duplicate subjects. Looking at an installation of Event Streams 3.1.4, the Rolebinding `ibm-eventstreams.v3.1.4-blahblah` has got 2 entries for the same service account:
```
subjects:
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-eventstreams.v3.1.4
```
At first I thought this was a bug with us, but searching through many open source and OCP NS-scoped operators I've noticed they all seem to have this duplication.

This is clearly not a critical issue, but it does look a little silly for a user to see.
Side-note, this duplication does not occur for cluster-scoped, so  I suspect this is happening in the code to handle setting permissions for single NS.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
```
subjects:
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-eventstreams.v3.1.4
```

**What did you see instead? Under which circumstances?**
```
subjects:
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-eventstreams.v3.1.4
```

**Environment**
* operator-lifecycle-manager version: 0.19.0

* Kubernetes version information:    v1.25.4+77bec7a

* Kubernetes cluster kind: 

**Possible Solution**

remove the duplicate subject for namespace scoped operators

**Additional context**
