### ISSUE TITLE
startingCSV blocks upgrades for dependent operators with nested OperatorGroups

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-lifecycle-manager#2984]
## Bug Report

**What did you do?**
I have 2 operators each with a dependency on a third operator in a single catalog:
`A -> C `
`B -> C`

I have two catalogs with these operators (just showing the channels):

catalog1:
`docker.io/cdjohnson/testcatalog@sha256:6a7da4528f0f3c46b4d8167733e024d4edf832ab7fcce59c2a3281aa3561c446`
```
schema: olm.channel
package: testoperatora
name: v1.0
entries:
  - name: testoperatora.v1.0.0
---
schema: olm.channel
package: testoperatorb
name: v2.0
entries:
  - name: testoperatorb.v2.0.0
---
schema: olm.channel
package: testoperatorc
name: v3.1
entries:
  - name: testoperatorc.v3.1.1

```

catalog2:
`docker.io/cdjohnson/testcatalog@sha256:bf48512e43435fe9f33e1b0475d5f47276efee8f22ac1e7fa1b7982bd79e51e7`
```
schema: olm.channel
package: testoperatora
name: v1.0
entries:
  - name: testoperatora.v1.0.1
    skipRange: <1.0.1
---
schema: olm.channel
package: testoperatorb
name: v2.0
entries:
  - name: testoperatorb.v2.0.1
    skipRange: <2.0.1
---
schema: olm.channel
package: testoperatorc
name: v3.1
entries:
  - name: testoperatorc.v3.1.2
    skipRange: <3.1.2
```

Steps:
1.  Apply `catalog1`
2.  Create subscription for A in AllNamesapces mode (openshift-marketplace)
    - This creates Subscription C with `spec.startingCSV: C-v3.1.1
    - This results in A 1.0.0 and C 3.1.1
3.  Create namespace `t1`
4.  Create OperatorGroup in `t1` for `t1` (OwnNamespace)
5.  Create subscription for B in namespace `t1`
    - This creates Subscription C with `spec.startingCSV: C-v3.1.1
    - This results in CSV's B 2.0.0 and C 3.1.1

Everything looks good.  Operator A & C is running in the global namespace, and Operator B is running in namespace `t1`.  Both A and B are depending on the same Operator C.

6.  Apply `catalog2`
    - A and C are upgraded in the global namespace to `1.0.1` and `3.1.2` respectively.
    - B is **NOT** upgraded to `2.0.1` in namespace `t1`

At this point, operator B will not upgrade.  No indication of an upgrade is available.

To upgrade:

7.  Edit the automatically generated subscription for operator C in namespace `t1` and REMOVE the `spec.startingCSV`
    - Once this is done, then Operator B is upgraded.

**What did you expect to see?**
I would have expected Operator B to be immediately upgraded to 2.0.1.

**What did you see instead? Under which circumstances?**
Operator B was not upgraded from 2.0.0 to 2.0.1 even though the catalog contained 2.0.1 and the dependency was satisified.

We suspect that this is a problem with the fact that the Automatically generated subscription for Operator C had a startingCSV set and this version no longer existed in the catalog or something similar.  

If we use `replaces` to keep version 2.0.0 of operator C in the catalog, then Operator B is upgraded automatically as expected:

`docker.io/cdjohnson/testcatalog@sha256:622be35c67c82481c45253655adb98c723665bc173b341850709b4c0c8cf851b`
```
schema: olm.channel
package: testoperatorc
name: v3.1
entries:
  - name: testoperatorc.v3.1.1
  - name: testoperatorc.v3.1.2
    replaces: testoperatorc.v3.1.1
    skipRange: <3.1.2
```

**Environment**
* OpenShift version 4.12.7

**Possible Solution**
- Stop creating the startingCSV for automatically generated subscriptions
- Ignore the startingCSV when resolving subsequent upgrades.

**Additional context**
