### ISSUE TITLE
ClusterRole and ClusterRolebinding are not deleted when operator is uninstalled

### ISSUE THREAD

**Issue by youhangwang** [operator-framework/operator-lifecycle-manager#2985]
## Bug Report

**What did you do?**

I have created a catalogsource and used it to install the operator.

In my repo, I add some addtional clusterrole and clusterrolebindings, Here is the details:
```
~ tree
.
...
├── manifests
│   ├── bases
│   │   └── operator.clusterserviceversion.yaml
│   └── kustomization.yaml
├── rbac
│   ├── bootstrap_cluster_role.yaml
│   ├── bootstrap_cluster_role_binding.yaml
│   ├── bootstrap_sa.yaml
│   ├── kustomization.yaml
│   ├── role.yaml
│   ├── role_binding.yaml
│   └── service_account.yaml
```
```
✗ cat config/rbac/kustomization.yaml 
......
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- bootstrap_cluster_role.yaml
- bootstrap_cluster_role_binding.yaml
- bootstrap_sa.yaml      
....
```

I install operator via the catalogsource, and the bootstrap_cluster_role, bootstrap_cluster_role_binding, bootstrap_sa are created successfully.

However, these three reources only have label:
```
  labels:
    olm.owner: xxx-operator.v2.6.0-1768300
```

the rbac created by the csv have the following labels:
```
  labels:
    olm.owner: xxx-operator.v2.6.0-1768300
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: xxxx
    operators.coreos.com/isf-operator.xxxxx: ''
```

when I uninstall the operator, the rbac with label:
```
  labels:
    olm.owner: xxx-operator.v2.6.0-1768300
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: xxxx
    operators.coreos.com/isf-operator.xxxxx: ''
``` 
are deleted automatically, but these rbac reources only have label `olm.owner` are not deleted

**What did you expect to see?**

these two rbac resource will also be deleted automaticallly

**What did you see instead? Under which circumstances?**

these two rbac resource is not deleted automaticallly.

But if I manuly add the following labels into thest two resources:
```
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: xxxx
    operators.coreos.com/isf-operator.xxxxx: ''
```
they will be deleted automatically when I uninstall the operator.

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
