### ISSUE TITLE
Add new Kind: OperatorConfig OR encapsulate its functionality

### ISSUE THREAD

**Issue by aRustyDev** [operator-framework/operator-lifecycle-manager#3039]
## Feature Request

**Disclaimer** : FNG here, very likely that I'm missing some already defined resource.

### The Problem
I am trying to use Terraform to automated and document my clusters deployment. I am using a combination of Helm and OLM to try and deploy both managed and unmanaged applications. But I have some applications that need to manage external cloud resources like S3, Route53, or Certificates and require setting annotations or application settings like shown in the [external-secrets-operator](https://artifacthub.io/packages/olm/community-operators/external-secrets-operator)

**Example**
```yaml
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
   requests:
     cpu: 10m
     memory: 96Mi
   limits:
     cpu: 100m
     memory: 256Mi
```

### Possible Solutions
1. Basically just copy the external-secrets Kind `OperatorConfig`.
2. Encapsulate the `OperatorConfig` functionality into the Kind `Subscription`

**Example 1**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
   requests:
     cpu: 10m
     memory: 96Mi
   limits:
     cpu: 100m
     memory: 256Mi
```

**Example 2**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: myApp
spec:
  package: myApp
  channel: alpha
  config:
    env:
      - name: ARGS
        value: "-v=10"
    clientSpecs:                <---- Shiny
      prometheus.enabled: True  <---- New
      service.port: 8080        <---- Feature
    resources:
     requests:
       cpu: 10m
       memory: 96Mi
     limits:
       cpu: 100m
       memory: 256Mi
```
