### ISSUE TITLE
VolumeMount not replace existing item by name

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [operator-framework/operator-lifecycle-manager#3131]
## Bug Report

**What did you do?**
[subscription-config](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#volumemounts)
VolumeMount not replace existing item by name

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: minio
spec:
  channel: stable
  name: minio-operator
  source: redhat-certified-operators
  sourceNamespace: olm
  config:
    env:
    - name: OPERATOR_STS_ENABLED
      value: "off"
    - name: MINIO_OPERATOR_RUNTIME
      value: "Rancher"
    volumes:
      - name: tmp
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: private.key
                    path: private.key
                  - key: public.crt
                    path: public.crt
                name: console-tls
                optional: true
    volumeMounts:
      - name: tmp
        mountPath: /tmp/certs
```

**What did you expect to see?**
OLM operator replace a mountPath in existing item by name

**What did you see instead? Under which circumstances?**
OLM operator trying to add new item with existing name

**Environment**
* operator-lifecycle-manager version: 0.26.0

* Kubernetes version information: 1.26

* Kubernetes cluster kind: RKE2

**Possible Solution**
[Suggested Method](https://github.com/operator-framework/operator-lifecycle-manager/blob/d70de0797c1604cb2b6d6aa043e1e7731fc830e3/pkg/controller/operators/olm/overrides/inject/inject.go#L121C8-L121C8)
```Go
func InjectVolumeMountsIntoDeployment(podSpec *corev1.PodSpec, volumeMounts []corev1.VolumeMount) error {
	if podSpec == nil {
		return errors.New("no pod spec provided")
	}

	for i := range podSpec.Containers {
		container := &podSpec.Containers[i]
		container.VolumeMounts = mergeVolumeMounts(container.VolumeMounts, volumeMounts)
	}

	return nil
}
```

**Additional context**
[Original Manifest Minio Operator](https://github.com/minio/operator/blob/3873db707c0c3265d5fd931eb886b0d3026a48f1/certified-operators/manifests/minio-operator.clusterserviceversion.yaml#L579C16-L579C34)
