### ISSUE TITLE
OLM generate bundle silently drops k8s resources existing in manifests

### ISSUE THREAD

**Issue by totahuanocotl** [operator-framework/operator-lifecycle-manager#3196]
## Support
Help around the operator-sdk generate bundle

## Question
How can I include k8s resources that are not part of the k8s core apis, or config-maps generated by kustomize?

**What did you do?**
Alongside my operator, I want to rollout k8s resources that are not part of the core apis as well as a kustomize generated config map.
Specifically, I want to deploy the following:
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: my-secret
spec: ...
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: another-sa
  namespace: system
---
kind: ConfigMap
metadata:
  name: config
...
```

**What did you expect to see?**
I expect:
1. the contents of the bundle to contain said resources amongst the `bundle/manifests`:
```
bundle/manifests
    another-sa_v1_serviceaccount.yaml
    my-secret_v1beta1_vaultstaticsecret.yaml
    config_v1_configmap.yaml
```

2. the configmap to be created as part of the installation of the CSV

**What did you see instead? Under which circumstances?**
Bundle Creation:
- While `another-sa` and `config` are present in the bundle, `my-secret` is missing from the bundle.

Operator Deployment:
- When installing the CSV, `config` is not created in the target cluster, and the operator deployment can't start.

**Environment**
* operator-sdk version:

```
operator-sdk version: "v1.33.0", commit: "542966812906456a8d67cf7284fc6410b104e118", kubernetes version: "1.27.0", go version: "go1.21.5", GOOS: "linux", GOARCH: "amd64"
```

* Kubernetes version information:

```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.10-eks-508b6b3
```
  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.
