### ISSUE TITLE
olmCAKey mounted as ca.crt

### ISSUE THREAD

**Issue by blezoray** [operator-framework/operator-lifecycle-manager#3480]
Hello,

I'm working on Openshift cluster 4.14/4.15 and I'm trying to integrate External Secrets Operator v0.12.1 (ESO) natively with OLM (until now, they use the helm operator SDK).
So I created a custom csv for it in a custom catalog. In it, there are 2 deployments : one for the controller and one for the webhook. When I create the subscription, everything is created correctly but the webhook pod failed to start correctly and reported this error:
```
{"level":"info","ts":1736170175.0750523,"logger":"setup","msg":"validating certs"}
{"level":"error","ts":1736170175.0751193,"logger":"setup","msg":"invalid certs. retrying...","error":"open /tmp/k8s-webhook-server/serving-certs/ca.crt: no such file or directory","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:219\ngithub.com/external-secrets/external-secrets/cmd.init.func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:88\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:283\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:22\nruntime.main\n\t/opt/hostedtoolcache/go/1.23.4/x64/src/runtime/proc.go:272"}
```
After discussion with ESO support, the webhook contains a check at start in order to verify the CA of webhook. Unfortunately, the `ca.crt` is not mounted even if it exists in the webhook secret, in the olmCAKey field.
```yaml
      volumes:
      - name: apiservice-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
          secretName: external-secrets-webhook-service-cert
      - name: webhook-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: external-secrets-webhook-service-cert
```

Is there a tip to mount the olmCAKey as ca.crt ?

**Comment by blezoray** [comment]
Hi,

the solution is there:
- use a specific path to mount the webhook service secret, `/tmp/olm-webhook-server/serving-certs`
- add `volumes` and `volumeMounts` with the good params. change the default secret name to avoid any conflict with the default mount done by OLM
- configure the webhook pod to use the good path, option `--cert-dir`

```yaml
                  args:
                  - webhook
                  - --port=10250
                  - --dns-name=external-secrets-webhook-service.mpms-external-secrets-operator.svc
                  - --cert-dir=/tmp/olm-webhook-server/serving-certs
                  - --check-interval=5m
                  - --metrics-addr=:8080
                  - --healthz-addr=:8081
                  - --loglevel=debug
                  - --zap-time-encoding=epoch
                  ports:
                  - containerPort: 8080
                    protocol: TCP
                    name: metrics
                  - containerPort: 10250
                    protocol: TCP
                    name: webhook
                  readinessProbe:
                    httpGet:
                      port: 8081
                      path: /readyz
                    initialDelaySeconds: 20
                    periodSeconds: 5
                  volumeMounts:
                  - mountPath: /tmp/olm-webhook-server/serving-certs
                    name: olm-webhook-cert
                volumes:
                - name: olm-webhook-cert
                  secret:
                    secretName: external-secrets-webhook-service-cert
                    defaultMode: 420
                    items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
                    - key: olmCAKey
                      path: ca.crt
```

With this config, it works fine.
