### ISSUE TITLE
Question: How to "enable" the OLM in the console for Minishift ?

### ISSUE THREAD

**Issue by rhuss** [operator-framework/operator-lifecycle-manager#538]
![image](https://user-images.githubusercontent.com/99080/47498100-854ff200-d85c-11e8-9481-9bf07a7ffc97.png)

I have added the "myproject" as watchname space:

```yaml
spec:
  containers:
  - command:
    - /bin/olm
    - -watchedNamespaces
    - myproject
    - -debug
    env:
    - name: OPERATOR_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OPERATOR_NAME
      value: olm-operator
    image: quay.io/coreos/olm:local
```

but that seems to be not good enough. What else would I need ?
