### ISSUE TITLE
Use CR definitions instead of configmap data

### ISSUE THREAD

**Issue by odra** [operator-framework/operator-lifecycle-manager#644]
Hello,

I just would like to ask if it makes sense to use the catalog source CR instead of a configmap, since managing multiple CSVs and CRDs in a configmap field can become a bit messy is you have lots of those.

Does it make more sense to add that info into the catalog source object instead?
It could use the same three fields used in the configmap but they could each be a list of their relative CRs:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  generation: 1
  name: custom-operators
spec:
  displayName: My Operators
  publisher: myself
  sourceType: embedded
  data:
    clusterServiceVersions:
      - csv-name1
      - csv-name2
      - csv-name3
    customResourceDefinitions:
      - crd-name1
      - crd-name2
      - crd-name3
    packages:
      - pkg-name1
      - pkg-name2
      - pkg-name3
``` 

It could also use some kind of label matching so it could scale a bit better (no need to list all dependencies in the catalog source cr):

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  generation: 1
  name: custom-operators
spec:
  displayName: My Operators
  publisher: myself
  sourceType: selector
  selector:
    matchLabels:
      catalog: custom-operators
```
