### ISSUE TITLE
Add helm chart to the release  

### ISSUE THREAD

**Issue by eyusupov** [operator-framework/operator-lifecycle-manager#829]
OLM is already using

**Comment by ekarlso** [comment]
Anyone from the devs care to weigh in on this?

**Comment by ecordell** [comment]
We don't intend to continue to use helm as our templating layer forever, so this has not been a high priority for us.

**Comment by RichiCoder1** [comment]
+1 for this, if only because it makes it super easy to use a tool like Flux to manage the OLM (which then manages everything else :D)

**Comment by kfox1111** [comment]
If folks step up to support this, would the project accept the pr's? It seems like a useful thing to support.

**Comment by RichiCoder1** [comment]
Bump

**Comment by mkilchhofer** [comment]
Bump again. I am also interested in having a helm chart for managing OLM.

**Comment by timothymathison** [comment]
I'm also interested in this capability, so that we can manage the installation with the terraform helm provider.

**Comment by ikorzh** [comment]
This is good idea.
I am also interested in having a helm chart for managing OLM

**Comment by yelhouti** [comment]
interested in this two please

**Comment by sathieu** [comment]
I've published the chart here: [https://gitlab.com/kubitus-project/external-helm-charts](https://gitlab.com/kubitus-project/external-helm-charts/-/blob/main/README.md#operator-lifecycle-manager).

It'll be updated automatically when new olm versions appears.

**Comment by chrisdewar** [comment]
Above gitlab.com link 404's for me... any update on this?

**Comment by sturman** [comment]
@sathieu @chrisdewar Looks like the git repo has been moved to https://gitlab.com/kubitus-project/external-helm-charts/operator-lifecycle-manager.  Helm repository address has not been changed and it still is https://gitlab.com/api/v4/projects/29255838/packages/helm/stable as mentioned in [README](https://gitlab.com/kubitus-project/external-helm-charts/operator-lifecycle-manager#operator-lifecycle-manager). Also you can check available Helm repository packages in [GitLab packages](https://gitlab.com/kubitus-project/external-helm-charts/operator-lifecycle-manager/-/packages)

**Comment by sathieu** [comment]
@chrisdewar Sorry, I've just updated the URL above. As @sturman said, the repo has moved.

**Comment by sturman** [comment]
@sathieu the chart version 0.19.1 is not found in the repository. I can see version 0.19.0 only
```shell
user@think-t460p:~/projects$ helm search repo lifecycle
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION                
operator-lifecycle-manager/olm	v0.19.0      	           	A Helm chart for Kubernetes
user@think-t460p:~/projects$ 
```

**Comment by sathieu** [comment]
@sturman I don't have the same result:

```
$ helm repo add operator-lifecycle-manager https://gitlab.com/api/v4/projects/29255838/packages/helm/stable
"operator-lifecycle-manager" has been added to your repositories

$ helm search repo operator-lifecycle-manager
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                
operator-lifecycle-manager/olm  v0.19.1                         A Helm chart for Kubernetes

$ helm search repo operator-lifecycle-manager -l
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                
operator-lifecycle-manager/olm  v0.19.1                         A Helm chart for Kubernetes
operator-lifecycle-manager/olm  v0.19.0                         A Helm chart for Kubernetes
```

You are probably using the [old](https://gitlab.com/kubitus-project/external-helm-charts/operator-lifecycle-manager/-/merge_requests/10/diffs) [repo](https://gitlab.com/kubitus-project/external-helm-charts/operator-lifecycle-manager/-/merge_requests/11):

```
$ helm repo add operator-lifecycle-manager-old https://gitlab.com/api/v4/projects/29255838/packages/helm/operator-lifecycle-manager
"operator-lifecycle-manager-old" has been added to your repositories

$ helm search repo operator-lifecycle-manager-old -lNAME                                    CHART VERSION   APP VERSION     DESCRIPTION                
operator-lifecycle-manager-old/olm      v0.19.0                         A Helm chart for Kubernetes
operator-lifecycle-manager-old/olm      v0.18.3                         A Helm chart for Kubernetes
operator-lifecycle-manager-old/olm      v0.18.1                         A Helm chart for Kubernetes
```

Some context: We needed this chart for [Kubitus Installer](https://gitlab.com/kubitus-project/kubitus-installer), to install Keycloak  Operator. Kubitus installer installs a full-featured Kubernetes cluster "batteries included" (see readme). It's still alpha, but [beta](https://gitlab.com/kubitus-project/kubitus-installer/-/issues?milestone_title=beta) is expected around December 2021.

**Comment by nwmcsween** [comment]
This can be done with argocd, specifiy the git repo and and targetRevision (release-xyz) add the helm `deploy/chart` as the helm dir and have gitops based OLM deployment.

**Comment by danielloader** [comment]
For those using flux V2, this seems to work:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: ">= v0.23.1"
  url: https://github.com/operator-framework/operator-lifecycle-manager.git
  ignore: |
    # exclude all
    /*
    # include chart
    !/deploy/chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./deploy/chart/
      sourceRef:
        kind: GitRepository
        name: olm
        namespace: flux-system
      interval: 1m
```
