### ISSUE TITLE
Service and ConfigMap specification in ClusterServiceVersion

### ISSUE THREAD

**Issue by sunsingerus** [operator-framework/operator-lifecycle-manager#972]
We are developing operator for ClickHouse and met the following issue(s) with `ClusterServiceVersion`.
1. Our operator exports Prometheus metrics and we have `kind: Service` object to provide stable connection point for this. How can `kind: Service` object be specified in `ClusterServiceVersion` along with `.spec.install.spec.deployments`? Or may be there is another approach preferred - like operator creates `kind: Service` object by itself via k8s API?
1. Our operator has configuration files and some templates provided to it as `kind: ConfigMap` objects mounted as volumes in operator's `Deployment`, like:
```yaml
      volumes:
        - name: etc-clickhouse-operator-folder
          configMap:
            name: etc-clickhouse-operator-files
```
How these `kind: ConfigMaps` objects can be specified in `ClusterServiceVersion` along with `.spec.install.spec.deployments` and mounted into operator's `Deployment`? Or may be there is another approach for this?
What would be correct way to bundle operator with additional required objects into `ClusterServiceVersion`? What to do in case operator requires some configuration files (default and changeable by user) and network services?

Thanks in advance!
